### ISSUE TITLE
How to calculate input-feature unit-output maps?

### ISSUE THREAD

**Issue by Harmageddon** [braindecode/braindecode#118]
Hi! First of all, thank you for your interesting work and for publishing and documenting everything here! :-)

For my master's thesis, I'm trying to classify the attentive state of patients with disorders of consciousness. The major challenge is that there is no ground truth available for these patients. To tackle this, I have two approaches. First, I'm using a Keras implementation of your deep network in combination with learning mechanisms that are robust to label noise. After training, gaining insight into what the network learned is the second aspect I'd like to investigate. So the input-feature unit-output correlation maps seem to be a promising method. I followed your tutorial on [Amplitude Perturbation Visualization](https://braindecode.org/auto_examples/perturbation.html), which worked using the learned model's prediction function. 
But regarding the input-feature unit-output correlation maps (without the perturbation), I don't know how I can calculate them. I read through the classes in the visualization package, but I'm not sure where to start. My goal would be an evaluation similar to figures 6/7 in your paper.

Can you point me in the right direction?

Kind regards, Constantin

**Comment by robintibor** [comment]
Hi! 
Sure! The example you linked to is unfortunately outdated, based on old braindecode version. We will have to update it :) To see how it works in the new braindecode, you can have a look at https://colab.research.google.com/drive/1cHFiXN31ycQ9SuTURy9aEyVRcsPjUWW_

Regarding the input-output correlation, we didn't supply code for it so far, but basically idea is : 
1. Bandpass filter the input data to different frequency ranges using mne
2. Compute the envelope (see https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.hilbert.html)
3. Correlate these envelopes with the activations of the network at different layers, both for a trained an untrained network.
4. Compute mean absolute correlations per sensor (mean over time and network output units of a specific layer), yielding two vectors per frequency range and per sensor (one for trained, one for untrained network)
5. Compute difference of these two vectors per frequency range and per sensors
6. Visualize the difference vectors as topographical plots using mne as in https://colab.research.google.com/drive/1cHFiXN31ycQ9SuTURy9aEyVRcsPjUWW_

Does this help you get started? Would you need a full code example?

**Comment by robintibor** [comment]
The whole procedure is a bit compute-intensive for computing all the bandpassfilters+envelopes

**Comment by Harmageddon** [comment]
Thank you for your answer! That already helps. I think I got it figured out now.

I understand that, for example, to compute the correlation for "Filter 1", you take the activations from the first conv block for each EEG channel separately, average over the temporal axis (?), calculate the correlation between this matrix which is `[n_samples x layer output units]` and the mean squared envelope which is `[n_samples x time]`, to get a correlation matrix of `[layer output units x time]` and then just take the mean from that. Is this correct?

**Comment by robintibor** [comment]
so I decided I will have a go at it myself:
https://colab.research.google.com/drive/1DsgVf_GWdy85urKpcSrn3yRdSsL89bVG#scrollTo=Y0t3kFg5WQ9Y
(scroll down for visualization)

It's a bit complicated, we can see if we can make some more helper functions to make this easier :)

Visualization is only done for one specific layer and frequency range.

**Comment by Harmageddon** [comment]
Awesome, thank you!
So if I see it correctly, I have to delete "average over the temporal axis" from my previous comment and instead reshape the activations from `[n_samples x layer output units x receptive field]` to `[layer output units x (n_samples * receptive field)]`. For the envelopes, I have to use a movavg to get them from `[n_channels x n_samples x time]` to `[n_channels x (n_samples * receptive field)]`. Then correlate both and get a correlation matrix of `[n_channels x layer output units]` for each frequency band.

**Comment by robintibor** [comment]
yes indeed one should not average activations over time before doing the correlation, as you want to see also temporally, if envelope goes up or down, does activation go up or down with it or not?

**Comment by Harmageddon** [comment]
That makes perfectly sense. I was puzzled about having one dimension too many, but of course, concatenating along the temporal axis works fine here.

I think I'll get it to work for my application from here. Thank you for your fast and good explanations! :-)

**Comment by xiaolongwu0713** [comment]
> Thank you for your answer! That already helps. I think I got it figured out now.
> 
> I understand that, for example, to compute the correlation for "Filter 1", you take the activations from the first conv block for each EEG channel separately, average over the temporal axis (?), calculate the correlation between this matrix which is `[n_samples x layer output units]` and the mean squared envelope which is `[n_samples x time]`, to get a correlation matrix of `[layer output units x time]` and then just take the mean from that. Is this correct?



> so I decided I will have a go at it myself:
> https://colab.research.google.com/drive/1DsgVf_GWdy85urKpcSrn3yRdSsL89bVG#scrollTo=Y0t3kFg5WQ9Y
> (scroll down for visualization)
> 
> It's a bit complicated, we can see if we can make some more helper functions to make this easier :)
> 
> Visualization is only done for one specific layer and frequency range.

HI, this notebook give error below:
AttributeError: module 'torch' has no attribute 'irfft'

Also the https://braindecode.org/ seems removed all content related with visualization. I am have some trouble to understand the correlation plot, could you please give me a working example?
