### ISSUE TITLE
Transforms->Preprocessors?

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#119]
While rewriting and refactoring for new tutorials, I thought about one possible renaming: Transforms->Preprocessors.
The reason is that our current transforms are applied directy to the data, not on-the-fly as torchvision transforms. This renaming would also allow to distinguish to-be-added transforms that are applied on-the-fly like in torchvision. However, don't feel 100% sure about it. What do you think @agramfort  @sliwy @gemeinl

**Comment by robintibor** [comment]
To give concrete example:

https://github.com/robintibor/braindecode-1/blob/refactoring/examples/plot_bcic_iv_2a_moabb_trial.py#L122-L131

naming would change there to preproc/preprocess

**Comment by agramfort** [comment]
and transforms would be on the fly augmentation techniques for example?

>

**Comment by robintibor** [comment]
yes exactly.

**Comment by agramfort** [comment]
sounds good !

>
