### ISSUE TITLE
CircleCI redownloads

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#120]
Is there a reason for the `force_update=True` introduced in https://github.com/braindecode/braindecode/commit/01aa0ce9283597e95a8263a39c70301a8e4eab0d ?

These lines https://github.com/braindecode/braindecode/blob/01aa0ce9283597e95a8263a39c70301a8e4eab0d/.circleci/config.yml#L93-L97

seem to lead to quite long downloads in case there is a example different from master branch as far as I understand.

See e.g. https://app.circleci.com/pipelines/github/braindecode/braindecode/340/workflows/75971e52-7fec-47ea-a4b9-ffdc114e2410/jobs/398/steps

Wouldn't update_path=False, force_update=False work? This is what we do inside code usually (force_update=False per default from mne), e.g. 
https://github.com/braindecode/braindecode/blob/01aa0ce9283597e95a8263a39c70301a8e4eab0d/examples/plot_skorch_crop_decoding.py#L43-L45

Or will this break CircleCI completely again? Annoying to wait for long times in new pull requests always redownloading same stuff, even multiple times :/ @agramfort

**Comment by agramfort** [comment]
give it a try. Yes it should be possible to avoid redownloads using
circleci caching

>

**Comment by robintibor** [comment]
thanks that solved it
