### ISSUE TITLE
Problem with create_windows_from_events working on an personal dataset

### ISSUE THREAD

**Issue by CarlosCarPer** [braindecode/braindecode#135]
'm working on a laboratory EEG dataset and I modified a bit the library for not to work with the custom dataset tutorial of the documentation online but to work as with the dataset of the trialwise example. I added a copy of bnci.py script at moabb datsets an the example of trial wise decoding so I can get my datasets processed as close as posible as the results shown in documentation tutorials.

When I'm finally able to work with them, I recive the next error:

```
line 144, in create_window_from_events
    "All trial sizes should be the same if you do not supply"

AssertionError: All trial sizes should be the same if you do not supply a window size
```

Certainly, my dataset trials are no the same length, so I decided to call the funcion like:

`windows_dataset = create_fixed_length_windows(
    dataset,
    start_offset_samples=trial_start_offset_samples,
    stop_offset_samples=0,
    window_size_samples=100,
    window_stride_samples=100,
    drop_last_window=False,
    preload=True,
)`

But antoher error occurs:

```
line 129, in create_window_from_events
raise NotImplementedError('Trial overlap not implemented.')

NotImplementedError: Trial overlap not implemented.
```

I tried several variations, but I'm not able to discover what I'm doing wrong. What should I do?

I tried `create_fixed_length_windows` but it does only drive me to another error.

**Comment by agramfort** [comment]
can you share a code snippet based on a public dataset one can easily fetch
to replicate/understand the error?

>

**Comment by robintibor** [comment]
I assume in your first code example you called create_window_from_events and not create_fixed_length_windows.
The error indicates that your trials are overlapping so one trial is partly inside another trial. Is this intended? Then we can think to implement it.

**Comment by CarlosCarPer** [comment]
If I'm not mistaken, the `create_windows_from_events` function creates a window with a trial. I understand that the function can't create windows from our datasets since they have trials with random samples amounts (from 2000 to 5200, with 100 samples steps).I'm actually working on comparing the results obtained with the default public datasets with our own datasets, so I think the better comparison is to minimise the changes on the parameters. The length on the windows could be an interesting study topic, but I?m most worried about overlapping since it

**Comment by robintibor** [comment]
hm for sure we will be able to solve this and also make it more easy in the future for others!

So, in general, there are currently to ways to cut out fixed-length windows (we will rename create_fixed_length_windows, windows are always fixed length) from potentially variable length recordings or trials:
* you have trial start and stop markers already:   create_windows_from_events
* you don't have start and stop markers, each recording can be considered a trial: create_fixed_length_windows

Please also correct me if I am wrong @gemeinl .
The target error indicates somehow targets were not found in the dataset, if we get some example data we can verify it better. Dummy data is also fine like if you can just recreate a data of the same format/data structure filled with random data.

We are very interested in having an easy-to-understand and accessible library and quite obviously we are not there yet.  So please also keep writing what you tried, what you expected and what didn't work, it is very valuable to us. 

Hopefully next week we can solve your use case and then also improve the overall usage for everybody :)

**Comment by gemeinl** [comment]
Hi @CarlosCarPer,
I will try to explain a bit more how cutting of windows is done, maybe it will make things clearer and help solve the problem.

Case 1:
You have a dataset where subejcts perform tasks at specific times. The dataset hence includes events as start and stop marker (or duration) and event code. Each event corresponds to one trial. So you could have a signle recording with several trials, each having a different event code (= label). An example here would be motor imagery datasets as the BCIC IV 2a dataset.
```create_windows_from_events``` cuts windows corresponding to the start and stop markers defined in the annotations of the ```mne.Raw``` objects. Here, we do not support overlapping trials. Overlapping trials mean that the stop marker of one event is located later than the start marker of another trial. This would assign two (potentially different) labels to the same segment of data, say right hand movement as well as resting state.

Case 2:
You have a dataset where no tasks are performed, so trials as in the sense above do not exist. The dataset, however, might include descriptions that define some properties on a recording level, such as a disorder or disease, gender or age of a subject which can be used as a label. (The label is inferred from the ```pandas.DataFrame``` of each ```BaseDataset``` using the column that is named ```<target_name>```.)```create_fixed_length_windows``` takes a recording and splits it into windows by creating fake events and duplicating the label specified on recording level. If this process results in labels -1, this means that the label defined at recording level could not be inferred from the description.

**Comment by CarlosCarPer** [comment]
Hi, thank you for your help @gemeinl.

I created .mat files with the same format as the BNCI Compettiton Dataset 2a 001-2014 (a 1xS cell array called 'data, where S are the runs per session of a subject, and inside of each structure array there are the 'X', 'trial', 'y', etc.), so I think `mne.raw` is able to create the necessary annotations. The problem here I think is that, because the methodology used on the EEG recording, each run has diferent number of trials and the trials have different lengths (2000, 2200, 2100, 3000.... samples). The real problem is not on the different number of trials per run but the different lengths, I think.

The datasets files are too big that I can't post them here directly, so I created a Drive folder to share them (let me know if you recommend other way). There are two zips:

- [Python files and datasets](https://drive.google.com/file/d/19zHyIxYb_Wox9yWDntKYT76kVkHXpxIY/view?usp=sharing) with only the modified .py files on python and the datasets need to run them. The are two dataset from the BNCICD2a I used as reference.

- [MATLAB files and datasets](https://drive.google.com/file/d/1v0_iTjb6VGkzfh2m3fl395aBJ2xwfEOf/view?usp=sharing) with the .m files I created to format the datasets and the original datasets I had to reformat., if it is helpful for you to check them. It needs access permission for security reasons, even though the data is random.

For better comprehension I wrote respective Readme txt. I will write dataset description when I finally receive feedback from my lab if it's needed.

**Comment by robintibor** [comment]
Thank you very much, we are looking inside your data at the moment. So do I understand correctly that in one run, that trial gives the starting points of each trial, and trials always go on until the next trial starting point? and last trial goes until end of recording?

So, let's say for ```subA09MS1.mat```:
```
trial:->
[    1,  2001,  4101,  9001, 11301, 16101, 18301, 20701, 25501, 27501, 32501, 35101, 37201, 42301]
y: ->
[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]
```
implies:
trial 0 is from 1-2000 with label 1
trial 1 is from 2001-4100 with label 2
...
last trial is from 42301-end of recording with label 2

Is this correct?

**Comment by CarlosCarPer** [comment]
Yes, that's right. This is how I understood that the `trial` variable works in BCNI datasets.

**Comment by robintibor** [comment]
Ok I have create one example for you where I directly create and split X and y matrices for use with braindecode according to your specification:

https://gist.github.com/robintibor/297fae93c4ab4f29c901243eda870f77

Does it work for you like that? Please also note the comments:
```
idx_offset = 0 # set to -1 in case indices were matlab based,e.g. index 1 in matfile implies index 0 in python
``` 
```
        # I would also recommend to subtract -0.5 here from
        # X to make it more centered....
```

This assumes you did your preprocessing in matlab already and won't do further preprocessing in python. If this works fine for you we could also see how to make it easier.

**Comment by robintibor** [comment]
Also note that the accuracy printed refers to accuracy over *trials* not windows, so it already means the predictions that belong to the same trial and then computes the accuracy. There is no issue with variable-length trials, that is supported in braindecode.

**Comment by CarlosCarPer** [comment]
I saw the code and I'm now trying to run it on a .py file, but it returns me a new error. If I'm not mistaken the error tells me that it can't import `_check_windowing_arguments`, but it already exists. I attached screenshots for better comprehension. Maybe I need to update the lbrary because this issue is already solved?

![running solution](https://user-images.githubusercontent.com/66958931/87772522-27c6ba80-c822-11ea-976e-435ffa4892a3.PNG)
![_check_windowing_arguments](https://user-images.githubusercontent.com/66958931/87772519-272e2400-c822-11ea-8bcc-8725930b1154.png)


On the other hand, I **did not preprocess the data**. I'm aware of the existence of [an X and Y custom dataset example in the documentation](https://braindecode.org/auto_examples/plot_custom_dataset_example.html) but tried not to use it because there is no preprocessing applied there. I used matlab to make our datasets suitable for python loadmat and for moabb datasets, but I really prefer to do all I can in Python, to have all more centralised. Can I do the preprocess you do in the trialwise and cropped decoding (band pass filter and exponential moving standardization) with this x and y load or should I do it in matlab?

**Comment by robintibor** [comment]
ok then another try to get you what you really want:
https://gist.github.com/robintibor/a18fe4614d73e3478e759dc45de037e8

please also check for errors, in previous notebook the validation set was actually the trainin set :o 
now it doesn't seem to be able to generalize so far (valid accuracy at chance level).

**Comment by robintibor** [comment]
is the python data you supplied random data? then makes sense it is not improving on validation :)) and would be interesting if code as is works fine for real data (potentially after adapting the ` X = (run.X.T - 0.5) * 1e-6 # unclear if this results in volt..`)

**Comment by CarlosCarPer** [comment]
It works just perfect!
![Result](https://user-images.githubusercontent.com/66958931/88102064-3f45d080-cb9f-11ea-901f-e328c29869dc.PNG)

Yes, the data was randomised. I have to see more closely the results, but for now there is no error. Now I will study the effect of the different parameters (training and validating with all the data of an user or just with one session, the length of the windowsm etc) and will try to test the model with new data.

Thank you very much for all your effort, I don't know how to thank.

**Comment by CarlosCarPer** [comment]
I was told to test a trained and validated model to see its accuracy with the purpose of applying it to an online recording experiment or to decode the intention for the actuation of an exoskeleton.

https://gist.github.com/CarlosCarPer/596ad2786dd5d919147ef413c04ec018

This is what I have done so far. The accuracies are really low and I would like to know if I am testing the models correctly. Maybe the model is overfitting?

The code is the cropped example with a few implementations I made:

- Train, validate and test the model with single-session runs.
- Test the model
- Plot temporal values

**Comment by robintibor** [comment]
Hi,

thanks so much for your continued feedback, it seems `predict` is broken on our side.

You also can directly iterate through the dataset to get the windows.

See here for working example using `predict_proba`:
https://gist.github.com/robintibor/d5a3c83c35ca29e6842305702d4a4fb5

Best,
Robin

**Comment by robintibor** [comment]
So consider this fixed through https://github.com/braindecode/braindecode/pull/171 unless @CarlosCarPer or @sliwy disagrees
