### ISSUE TITLE
Import Error when importing create_from_X_y

### ISSUE THREAD

**Issue by Khalizo** [braindecode/braindecode#136]
Hi there, 

I have installed braindecode but get this error when trying to import create_from_X_y. Please how can I fix this?

![image](https://user-images.githubusercontent.com/22616237/86639239-84c7a280-bfd0-11ea-8579-3ea0494e0f08.png)

**Comment by robintibor** [comment]
Hi this due to a change in the code that has not been pushed to PyPI yet.
You can either update to current master or import via 

```python
from braindecode.datasets.xy import create_from_X_y
```

See https://github.com/braindecode/braindecode/blob/41a216572f08ef23fd0af47e10e89bc9179cce5e/examples/plot_custom_dataset_example.py also

**Comment by Khalizo** [comment]
Dear Robintibor,

Thanks for your swift response, I really appreciate all the work you
have done with this library!

I am also struggling with another issue. I am trying to predict levels of
attention using EEG signals from 8 channels, however I am not sure how to
convert it into a brain decode format.

My "X" is a dataframe with shape (2400, 8):
[image: image.png]

While my "y" has shape (2400,):
[image: image.png]

How can convert it into a format that is usable?

Thanks,
Babs

**Comment by robintibor** [comment]
So, as far as I see you want to predict attention level at each point? can you share your data? Then I could have a try as well to see what is best implementation for your use case and document it better.

**Comment by Khalizo** [comment]
Hi Robintibor,

Here is a sample file of 1 test from a single user. The user was given 5
different paragraphs to read and then gave a score between 1-5 of the level
of attention. 8 channels were used to record the EEG readings.

Please let me know if you have any questions.

Thanks,
Babs

**Comment by robintibor** [comment]
There seems to be no sample file can you attach it again or link to it somewhere?

**Comment by Khalizo** [comment]
Hi Robintibor,

Can you see it via this link below?
  user1_test10_attention.csv
<https://drive.google.com/file/d/1Y13SwJmUDYTmPsZd1DN-EH2FT6PGN2hx/view?usp=drivesdk>

Thanks,
Babs

**Comment by robintibor** [comment]
@sliwy seems to me this might be a use case for continuous classification, would you be interested to have a look how to do that? Maybe it's already possible using custom loss function, maybe sth extra has to be implemented, not sure

**Comment by Khalizo** [comment]
Hi Both,

My X_train is a 3D array with the shape (number of samples, timepoints,
channels) and my labels are in a 1D array (number of samples).

Please how can I use this library? Any help will be appreciated as the
project is urgent.

Thanks,
Babs

**Comment by sliwy** [comment]
@robintibor @Khalizo I will have look at it now and continue tomorrow morning, let you know about my insights!

**Comment by sliwy** [comment]
I don't know if I understood correctly, but it should be a standard classification problem. You should then modify the network in our classification example to have 5 neurons at the output (`n_classes=5`). You want to predict labels per trial, which you prepared and you have them in the `X_train` 3D array. You should be able to use the `create_from_X_y` function. 

This function takes as input an array with the dimensions order: `n_trials x n_channels x n_times`. In your naming, `n_trials` corresponds to number of samples, `n_times` to timepoints. You should run ```X_train = X_train.swapaxes(1, 2)``` before `create_from_X_y` to be consistent with the needed order of dimensions. After that, `create_from_X_y(X_train, y_train, drop_last_window=False, sfreq=sfreq, ch_names=ch_names)` should create you the dataset that you need for further training.

Generally, you should read the data as I described above and follow this example https://github.com/braindecode/braindecode/blob/41a216572f08ef23fd0af47e10e89bc9179cce5e/examples/plot_bcic_iv_2a_moabb_trial.py replacing the `n_classes` value and the data reading code. 

I did not use your data because it does not correspond to the `X_train` array you described. You should add a trial number in the csv file to make it possible to read the data into a 3D array. I don't know how to split data into trials without it.

@Khalizo That is what I figured out based on your description. Let me know if my advice helped you.

**Comment by Khalizo** [comment]
Dear Maciej,

Thank you so much for your detailed explanation. I will give it a go today
and let you know how it goes.

Thanks,
Babs

**Comment by robintibor** [comment]
Hi,

since you indicated it is urgent, I had a quick try to see myself how to do it. I assume you want to cut out windows from the 2400 timepoints and then classify these.

Code example here: 
https://gist.github.com/robintibor/a22b99dc054d0e84d57ec9c50d90aa8e

However, two things:
1) This implementation by me is quite inefficient, if you have a lot of data it may be too slow. Please let us know if you need more efficient version, then we can try to implement it.
2) This is a very small amount of data, and results may be quite random (and even, only three classes appear in this data (3,4,5)

**Comment by robintibor** [comment]
Also, as updated, your data has very high standard deviation, so better to standardize it first (see updated notebook in link above)

**Comment by robintibor** [comment]
You could also try smaller window sizes to regularize the training more: https://gist.github.com/robintibor/59280edaa48030183536af4464f9b94a

**Comment by Khalizo** [comment]
Dear Robintibor,

Thank you so much for helping out here, really appreciate it! Managed to
get the shallowconvnet to work! 😀

One thing I noticed, was that the create_from_X_Y function prints out a lot
of information which slows down the process. Would be great if there was a
parameter for verbosity I.e Verbose = False, to prevent it from printing.
[image: image.png]

Moreover, I tried to load the deepconvnet but got this error:
"RuntimeError: Calculated padded input size per channel: (9 x 1). Kernel
size: (10 x 1). Kernel size can't be greater than actual input size"

I suspect that I need to add a value for "final_conv_length" but not 100%
sure what value to use:
[image: image.png]

Anytime help with this will be much appreciated!

Thank you,
Babs

**Comment by robintibor** [comment]
inside the ```create_from_X_y``` function, mne is printing things. you could try if https://mne.tools/stable/generated/mne.set_log_level.html helps.
If you are in the notebook you could also put %%capture on top of the cell to block/capture all output.

Regarding deep, I recommend to try adjusting 
```
        pool_time_length=2,
        pool_time_stride=2,
```
in deep4 constructor

**Comment by Khalizo** [comment]
Hi Robintibor,

Thank you for this, I gave it a try and managed to get it to work on
pool_time_length=1, pool_time_stride=1. So thanks for pointing me in the
right direction! :)

I have another query, I tried implementing bandpass filtering using this
library - https://github.com/hadrienj/EEG. However, it had a very negative
effect on performance. How can I use Braindecode's built-in preprocessing
module on my custom data?

 Assuming the data will be in a 2D  array i.e (#timepoints, #channels). I
tried myself (see below) but it looks like it needs an MNE dataset?

[image: image.png]

Thanks,
Babs

**Comment by robintibor** [comment]
somehow the image is not visible..... did you attach it here properly?

**Comment by Khalizo** [comment]
Hi Robintibor,

Here is the image that I attached before:
 image.png
<https://drive.google.com/file/d/12CQlf3TBBrKKhdKnn0W7YX9jpnpN8BoZ/view?usp=drive_web>

Nonetheless, I managed to resolve the issue by creating a custom function
for bandpass filtering.

Earlier you mentioned that the implementation you did in the workbook was
inefficient. How could things be sped up?

Thanks,
Babs

**Comment by Khalizo** [comment]
Additionally, I would like to implement early stopping to avoid overfitting
do you have any examples of this? I found the "remember_best_column
(string, optional)" in the fit function but not 100% sure how to use it or
whether it used for early stopping.

Thanks,
Babs

**Comment by robintibor** [comment]
ok, we see we need to more to allow creating datasets from X/y that allow further processing. The windows dataset coming out of creating form x/y should it be preprocessable in general @gemeinl ?

**Comment by robintibor** [comment]
For early stopping, check skorch: https://skorch.readthedocs.io/en/stable/callbacks.html#skorch.callbacks.EarlyStopping

**Comment by Khalizo** [comment]
Hi Robintibor,

Thanks for directing me to early stopping, much appreciated.
If you have any tips on how to speed up the process despite using a GPU,
please let me know.

Thanks,
Babs

**Comment by robintibor** [comment]
So the idea here involves some more complex code. Maybe @sliwy would be interested? :D 
We would need to support per-time-step labels in cropped decoding, which we should implement at some point anyways.
* we need to check if labels can be put inside as vectors or somehow keep the per-timestep labels in the dataset and through the skorch loop
* we need to check if one can just use a pytorch loss function without cropped wrapper and stuff just works?
* we need to check how the scoring stuff works best, like no meaning across time dimension as now assumed in cropped scoring
* we need to check our eegclassifier/Regressor interface, how to integrate it into it cleanly and nicely

so quite some work for a nice implementation,  @sliwy would you be interested to have a look?

**Comment by Khalizo** [comment]
Hi Robintibor,

Thanks for this!

I am trying to use the EEGRegressor but have been falling into some issues.
I have removed the softmax layer however the output dimension is still [32
x number of classes] and not sure how to reshape the output for the loss to
be calculated.

*This is the error message: *

UserWarning: Using a target size (torch.Size([32])) that is different
to the input size (torch.Size([32, 5])). This will likely lead to
incorrect results due to broadcasting. Please ensure they have the
same size.
  return F.mse_loss(input, target, reduction=self.reduction)


*Here is my code: *

# remove softmax
        new_model = torch.nn.Sequential()
        for name, module_ in model.named_children():
            if "softmax" in name:
                continue
            new_model.add_module(name, module_)

        model = new_model

        regressor = EEGRegressor(
        model,
        criterion=torch.nn.MSELoss,
#         criterion__loss_function=torch.nn.functional.mse_loss,
        optimizer=torch.optim.AdamW,
        train_split=predefined_split(validset),
        optimizer__lr=lr,
        optimizer__weight_decay=weight_decay,
        iterator_train__shuffle=True,
        batch_size=batch_size,
        callbacks=[
            "neg_root_mean_squared_error",
            # seems n_epochs -1 leads to desired behavior of lr=0
after end of training?
            ("lr_scheduler", LRScheduler('CosineAnnealingLR',
T_max=n_epochs - 1)),
           ("EarlyStopping", EarlyStopping(monitor = 'valid_loss',
threshold = 0.0001)),
        ],
        device=device)


Please let me knoow if you need any more information.


Thanks,

Babs

**Comment by robintibor** [comment]
did you set 
```python
    n_classes = 1
```
for the model construction?

**Comment by Khalizo** [comment]
Hi Robintibor,

Ahh no I didn't, will give it a try now.

Thanks!

Kind regards,
Babs

**Comment by gemeinl** [comment]
> ok, we see we need to more to allow creating datasets from X/y that allow further processing. The windows dataset coming out of creating form x/y should it be preprocessable in general @gemeinl ?

Well, originally, the ideas were
1) that if the user provides X/y then he took care of the preprocessing including the cutting of trials.
2) that preprocessing within braindecode can be applied both to raw as well as to epoched data (windows).

So, you should be able to apply bandpass filters on a windows level, like so:
```
preprocessors = [
    MNEPreproc("filter", l_freq=xx, h_freq=yy)
]
preprocess(windows, preprocessors)
```
Now what do we want in addition to this? An intermediate step of ```create_frm_X_y``` that returns 'raw' data that can be preprocessed prior to cutting windows? Did I get this right?

**Comment by robintibor** [comment]
I think I would be in favor of having a clear way to just create dataset with raws as well from x y but we need to think about how to best do it...

**Comment by gemeinl** [comment]
What about renaming ```create_from_X_y``` to ```create_from_trial_X_y``` and add a function ```create_from_windows_X_y```?
The first will give you a dataset of 'raws' which can be preprocessed and afterwards transformed into windows with ```create_fixed_length_windows```, and the latter will give you windows directly?

**Comment by Khalizo** [comment]
Hi Robintibor,

Please could you kindly explain cropped decoding? Does it speed up the
training process if my data has been cut with overlapping windows?

Thanks,
Babs

**Comment by robintibor** [comment]
Cropped decoding is explained in https://braindecode.org/auto_examples/plot_bcic_iv_2a_moabb_cropped.html
Initial issue is solved I think :)
