### ISSUE TITLE
Concat Concat Datasets

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#141]
Would be nice if BaseConcatDataset can deal with a list of BaseConcatDatasets in the constructor as well (so flattening them to list of BaseDatasets and then concatenating them in same logic as now). 

This allows for example following workflow:

* split raw dataset by some criterion like subject,
* now let's say train set should be subjects 'A', 'B', 'C' valid set subjets 'D', 'E'
* now you could call constructor of baseconcatdataset constructor with corresponding baseconcatdatasets

Right now you could use concatdataset from pytorch in that way, but then you could no longer use other braindecode functions, e.g. windowing.

How do you think @gemeinl ?

**Comment by gemeinl** [comment]
Great idea, I like it. Will see what I can do.
