### ISSUE TITLE
Default sfreq in create_from_X_y

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#143]
In ```create_from_X_y```, a default sampling frequency is specified, if the user did not provide one, see: https://github.com/braindecode/braindecode/blob/master/braindecode/datautil/xy.py#L46.
I think this is dangerous and should be removed. When creating a dataset from ```Xy```, specifying ```sfreq``` should not be optional but mandatory. The user has to know the sampling frequency, since it might be essential later on, e.g. for following transformations or preprocessing.

**Comment by robintibor** [comment]
So change this and put a note in the docstring informing about previous and new behavior

**Comment by dcwil** [comment]
@vytjan, @AnnKathrinKiessner, @HenrikBons, and I will be having a go at this!
