### ISSUE TITLE
Decrease the dependencies on MOABB

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#150]
Originally we thought of MOABB as a soft dependecy; a nice way to fetch data and start right away.
We should probably remove MOABB from our tests and from most of our examples.

**Comment by agramfort** [comment]
if you put it in examples it's a soft dependency. Yes for tests it's
maybe an overkill.
Having one good dataset like sample or testing (which is a small
sample) we use in mne test is
to me a good trade off

having moabb in example to demo on real dataset without having to
maintain here the
fetchers seems a good idea to me

**Comment by OleAd** [comment]
Related, in #196 MOABB as of now requires jumping through a lot of hoops to get working.

**Comment by ErikBjare** [comment]
@OleAd MOABB now requires *fewer* hoops to get working than before, see #201.

**Comment by robintibor** [comment]
We still use MOABB in quite some tests (dataset/windower tests) but do we consider this a problem? to me seems ok or at least not high priority to remove, what do you think @gemeinl ...

**Comment by sylvchev** [comment]
Hi, MOABB should be easier to integrate now. Let me know how we could help to ease the process. We also have refactor the code to download datasets, it should be more reliable and stable.

**Comment by robintibor** [comment]
We could still see if we could remove moabb dataloading and replace it with fake datasets just to make things more decoupled

**Comment by robintibor** [comment]
Somehow it seems on a fresh install moabb will fail if you do not create ~/mne_data ? this made our CI fail temporarily... is this intended, wasn't it different before?

**Comment by sylvchev** [comment]
No, it is a bug! We simplify the storage of datasets, and this error passed through our CI. I'll push a fix right now.

**Comment by sylvchev** [comment]
Ok, it is corrected : https://github.com/NeuroTechX/moabb/pull/204

**Comment by robintibor** [comment]
great

**Comment by bruAristimunha** [comment]
Hello @gemeinl, @agramfort, @robintibor, @sylvchev,

I understand that this issue has been discussed and debated. Can we close this issue?
