### ISSUE TITLE
Test a trained model

### ISSUE THREAD

**Issue by CarlosCarPer** [braindecode/braindecode#151]

**Comment by CarlosCarPer** [comment]
I'm working on a research thesis with the repository and I was told to test a trained and validated model to see its accuracy with the purpose of applying it to an online recording experiment or to decode the intention for the actuation of an exoskeleton.

https://gist.github.com/CarlosCarPer/596ad2786dd5d919147ef413c04ec018.js

This is what I have done so far. The accuracies are really low and I would like to know if I am testing the models correctly.

The code is the cropped example with a few implementations I made:

- Train, validate and test the model with single-session runs.
- Test the model
- Plot temporal values

**Comment by robintibor** [comment]
considered outdated through https://github.com/braindecode/braindecode/pull/171 , otherwise reopen
