### ISSUE TITLE
test_trialwise_decoding fails 

### ISSUE THREAD

**Issue by hubertjb** [braindecode/braindecode#153]
On current master (commit 462028a7b77d2a1751f8526de4fbd8122d56f92c) the acceptance test `test_trialwise_decoding` fails for me. The train loss for instance is different from the values hardcoded in the test.

In test:
[1.1114974617958069,
 1.0976492166519165,
 0.668171226978302,
 0.5880511999130249,
 0.7054798305034637,
 0.5272344648838043]

On CPU, torch==1.4.0:
[1.1114973425865173, 0.6608118116855621, 0.8881862759590149, 0.5603521466255188, 0.6126846820116043, 0.3842557668685913]

I also tried on GPU for fun:
[0.949962854385376, 0.9517839550971985, 0.7434093356132507, 0.6833578497171402, 0.9080942273139954, 0.3789084255695343]

@robintibor @sliwy would you know why this fails?

**Comment by sliwy** [comment]
I think that it may be connected with #134. It fails with `skorch` version 0.8. Can you check if it works with `skorch==0.7`?

**Comment by hubertjb** [comment]
Ah good catch @sliwy! It does work with `skorch==0.7`. 

I took a quick look at the changes from 0.7 to 0.8 but couldn't identify the culprit https://github.com/skorch-dev/skorch/compare/v0.7.0...v0.8.0. It seems like they've changed the fit loop, maybe that had an impact?

**Comment by agramfort** [comment]
can you make the test less strict so it works for both versions?

>

**Comment by hubertjb** [comment]
@agramfort I think it would be nice to understand what is behind this difference between versions... If it ends up being too complicated I can just modify the test though.

I've looked at the differences from 0.7 to 0.8 and I think it might be caused by the introduction of the new `PassthroughScoring` class as default for `NeuralNet` instead of `BatchScoring`. Could there be an interaction with EEGClassifer` @sliwy @robintibor ?

**Comment by robintibor** [comment]
yeah I agree we should look inside. Did not look at the PassthroughScoring class yet, but definitely such interactions may be there and cause problems. may try to have a look on friday

**Comment by hubertjb** [comment]
@robintibor that was fixed in #155 right?

**Comment by robintibor** [comment]
yep should be fixed, thanks for the notice
