### ISSUE TITLE
Scikit-learn API

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#154]
If I remember correctly, one of the reasons to use skorch was the similarity to the scikit-learn API.
However, in the rest of braindecode we lack support.
Should we add wrapper classes for our preprocessing functionality that inherit from ```TransformerMixin``` to allow for chaining everything in scikit-lean pipelines?
It could look similar to this:
https://gist.github.com/gemeinl/d64c014debb5f58e4feacb57a8656ed0

**Comment by agramfort** [comment]
we could go towards sklearn transformers and pipelines
I don't have a strong opinion unless you show me how the code could
look like compared to how it is now.

**Comment by gemeinl** [comment]
Check out this gist that shows our "Basic trialwise decoding" example updated to use scikit-learn API:
https://gist.github.com/gemeinl/d64c014debb5f58e4feacb57a8656ed0

**Comment by agramfort** [comment]
this is really nice ! do you see any potential limitation in this approach?
any computational overhead
or waste of computations?

>

**Comment by hubertjb** [comment]
Very nice example @gemeinl! I believe we had discussed using objects for windowers during the sprint? I think making full use of skorch would make a lot of sense.

**Comment by robintibor** [comment]
So is this still open or have we implemented it? @gemeinl

**Comment by gemeinl** [comment]
> So is this still open or have we implemented it? @gemeinl

What do you mean `have we implemented it`?
The code is in the notebook linked above. It was never merged into braindecode.
Should I do this? Where and how would I include this?

**Comment by Ardillen66** [comment]
Hello, my colleagues and I would be really interested in this functionality. Also, having an example that shows how to use braindecode models in a Scikit-learn Pipeline in the documentation would be really nice in my opinion.

**Comment by bruAristimunha** [comment]
Hello @Ardillen66!

Good suggestion! Are you interested in building a tutorial or improving any of the tutorials in the library? 

Braindecode is built on top of skorch. The fastest way to use the pipeline is to use the tutorial from skorch, using EEGClassifier or EEGRegression instead of the NeuralNet.

https://skorch.readthedocs.io/en/stable/user/quickstart.html#in-an-sklearn-pipeline

Please let me know if you have any other questions.

**Comment by Ardillen66** [comment]
I think that a separate tutorial showing some of the other examples with a Pipeline or expanding the existing examples with how to achieve the same thing with a Pipeline would be ideal.

I am currently rather busy, but I would be happy to expand the documentation when I have the time.

**Comment by bruAristimunha** [comment]
Nice @Ardillen66!

So we'll wait when you have time. Probably one more section in the tutorial for the next version of the braindecode: https://braindecode.org/master/auto_examples/plot_hyperparameter_tuning_with_scikit-learn.html
