### ISSUE TITLE
Reorganization of data-related modules

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#156]
From @gemeinl https://github.com/braindecode/braindecode/pull/152/files/fac6cea5d6ea0af49dcb39c85d3be33dfa791c22#r470535380 
Personally, I don't like the name "datautil" at all and feel like we could use some major refactoring here. My thoughts:
Currently, ``braindecode.datautil`` for me contains a mess of 
- Loading and saving datasets (``serialization.py``) 
- Creating datasets (``xy.py``, ``mne.py``)
- Preprocessing (``preprocess.py``)
- Creating windows ((``windowers.py``) which is also a bad name, since we don't have windower classes anymore). Also, creating windows is a kind of preprocessing

We could probably rename ``braindecode.datautil`` to ``braindecode.preprocessing`` with ``preprocessing.py`` which contains a merge of ``preprocess.py`` and ``windowers.py``.

We could add ``braindecode.serialization`` with ``serialization.py``

I am not so sure what to do about ``xy.py`` and ``mne.py``, though.

**Comment by agramfort** [comment]
what do you suggest @robintibor ? braindecode started as your "baby" so you
should have an opinion ;)

**Comment by robintibor** [comment]
Hm! 
Let's extend @gemeinl  List to also include what is in dataset:

- Loading and saving datasets (``serialization.py``) 
- Creating datasets (``xy.py``, ``mne.py``)
- Preprocessing (``preprocess.py``)
- Creating windows ((``windowers.py``) which is also a bad name, since we don't have windower classes anymore). Also, creating windows is a kind of preprocessing
- Base Dataset structure (``base.py``)
- Specific Existing Datasets (``bbci.py``, ``moabb.py``, ``tuh.py``)

Maybe what I could see:
- datasets
   - xy.py
   - mne.py
   - bbci.py
   - moabb.py
   - tuh.py
- preprocessing
  - preprocess.py
  - windower.py
- datautil
  - serialization.py
  - util.py

Another option would be deeper hierarchy, e.g.:
- io
  - datasets
     - xy.py
     - mne.py
     - bbci.py
     - moabb.py
     - tuh.py
  - preprocess.py
  - windower.py
  - serialization.py
  - util.py

**Comment by agramfort** [comment]
I like the first one better but I am wondering if the datautil module will
actually contain public functions. Maybe if it's 2 function to save and load
some models we can have 2 functions in the top namespace

>

**Comment by hubertjb** [comment]
+1 for option 1 with datautil in top namespace. Also, @robintibor did you want to combine windowers and preprocessing? If so we could do `from braindecode.preprocessing import ...` instead of `braindecode.preprocessing.preprocess import ...` which starts to feel a bit dense.

**Comment by robintibor** [comment]
So should I do first option now before sprint including deprecation? Or we keep as is? @hubertjb  @gemeinl @agramfort @sliwy

**Comment by agramfort** [comment]
+1 for me. Let's do option 1.
