### ISSUE TITLE
ERRORS when Run high-gamma-dataset example

### ISSUE THREAD

**Issue by TianhaoFu** [braindecode/braindecode#162]
Hi ， I‘m running your code in _https://gin.g-node.org/robintibor/high-gamma-dataset/_
but I had an error:

**ModuleNotFoundError: No module named 'braindecode.datautil.signalproc'**

It seems in your latest braindecode package the signalproc function was removed, what can i do next?

Thanks!

**Comment by robintibor** [comment]
We have high-performing decoding code at https://gist.github.com/robintibor/6a95a85088e651392c1bb4f912d1528e 
Would be worth it to transform to proper braindecode example.
Also @TianhaoFu linked code may be interesting for you
