### ISSUE TITLE
Download entire MOABB dataset

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#173]
MOABB Dataset could accept ```subject_ids=None``` which will download data of all subjects.

**Comment by agramfort** [comment]
+1

>

**Comment by robintibor** [comment]
did you need this functionality @gemeinl ? or why the thought to add it? don't have a problem with it just wondered what is motivation for it

**Comment by gemeinl** [comment]
Well, I just found it inconvenient to get started:
I am not too familiar with the BCIC IV 2a dataset but I wanted to do some decoding on all the subjects.
To download the data, I need to know how many subjects there are, so I either have to search the MOABB source code for the docstring with the dataset description or search for the corresponding publication. Of course, sooner or later one should read about the dataset one is using, but I think downloading could be done without requiring prior knowledge about the dataset.

Alternatively, instead of accepting ```subject_ids=None``` we could make the MOABB docstring available in Braindecode.

**Comment by robintibor** [comment]
ok understood. yeah why not both add subject_ids=None and make the docstring available

**Comment by robintibor** [comment]
This logic here may help to understand how to process docstrings of other functions:

https://github.com/braindecode/braindecode/blob/8f6f1406d85a0412f480662f07595ddeaca4d869/braindecode/util.py#L343-L355
https://github.com/braindecode/braindecode/blob/8f6f1406d85a0412f480662f07595ddeaca4d869/braindecode/regressor.py#L18-L47

**Comment by gemeinl** [comment]
@robintibor I do not see away of how to do this for general class `MOABBDataset`. We can only provide a docstring to our `BNCI2014001` and `HGD`, right?

**Comment by gemeinl** [comment]
Because the `MOABBDataset` docstring will be checked by the user prior to instantiation. But we will receive the name of the dataset the user actually wants to use just then.

**Comment by gemeinl** [comment]
Maybe one could create some kind of an overview table for the docstring of `MOABBDataset` which lists all the datasets fetchable through MOABB, the number of subjects and the pradigm. Could be a lot of work, though..
