### ISSUE TITLE
Preserve order when splitting datasets

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#174]
Splitting of datasets (https://github.com/braindecode/braindecode/blob/master/braindecode/datasets/base.py#L160-L162) should probably return an OrderedDict. For example, if data is split for subjects or enumerated runs, then iterating through the returned dictionary should contain data of subject or runs in ascending order.

**Comment by robintibor** [comment]
Please check if this is even necessary with current Python Version

**Comment by bruAristimunha** [comment]
Hi @robintibor and @gemeinl, 
I performed some tests and the order is being preserved in the split.

**Comment by robintibor** [comment]
great
