### ISSUE TITLE
ModuleNotFoundError: No module named 'moabb'

### ISSUE THREAD

**Issue by PeifengRen** [braindecode/braindecode#176]
from moabb.datasets.utils import dataset_list
ModuleNotFoundError: No module named 'moabb'
Thank for your answer!

**Comment by hubertjb** [comment]
Hi @985525078, can you confirm you have installed MOABB using the instructions in the [README](https://github.com/braindecode/braindecode#installation)? The error you're getting might just be that you don't have MOABB installed in your environment.

**Comment by 985525078** [comment]
thank，you

**Comment by ErikBjare** [comment]
@robintibor This can be closed.
