### ISSUE TITLE
Inconsistent assert

### ISSUE THREAD

**Issue by PierreGtch** [braindecode/braindecode#181]
I think there might be a problem with this definition : 
https://github.com/braindecode/braindecode/blob/818d51c40d77d24effa0220d6b82a3746a66bb44/braindecode/datautil/windowers.py#L141
and it should be : 
```python
this_trial_sizes = stops + trial_stop_offset_samples - (onsets  + trial_start_offset_samples)
```

Because the test line 147 then also requires  `trial_stop_offset_samples` to be 0.
https://github.com/braindecode/braindecode/blob/818d51c40d77d24effa0220d6b82a3746a66bb44/braindecode/datautil/windowers.py#L147

**Comment by gemeinl** [comment]
You are absolutely correct. Thanks for reporting.
Should be fixed via https://github.com/braindecode/braindecode/pull/184.

**Comment by robintibor** [comment]
Great
