### ISSUE TITLE
TypeError BBCIDataset

### ISSUE THREAD

**Issue by PierreGtch** [braindecode/braindecode#182]
I have a TypeError when loading BBCIDatasets for the high-gamma-datset.
It was reported and fixed in the TNTLFreiburg/braindecode repo but not in this one

Here is the fix:
https://github.com/TNTLFreiburg/braindecode/commit/fab1e24a627e81fd4445c78997bfde625a260383

**Comment by robintibor** [comment]
Fixed here as well through https://github.com/braindecode/braindecode/commit/38b5402ebb1efb66296f93343fff1ac9626a0030#diff-8ad72d10e5b9d8fa69cad3f9c6494022af3c44ff2f864fcb250f914f98da9028

**Comment by robintibor** [comment]
Thanks again for notice
