### ISSUE TITLE
How to Save a Trained Model without changing codes in the packages?

### ISSUE THREAD

**Issue by zinker8086** [braindecode/braindecode#191]
Hello, 
I've trained a new model with this package, and also I want to use the given ShallowNet model. So I'd like to save the trained models with the best performance. Do you know how to deal with that circumstances?

**Comment by agramfort** [comment]
if you have an EEGClassifier you have a skorch instance so you should be
able to use : https://skorch.readthedocs.io/en/stable/user/save_load.html

you have also the trained module in clf.module

then you can read
https://pytorch.org/tutorials/beginner/saving_loading_models.html

HTH

**Comment by zinker8086** [comment]
Thank you for answering.
