### ISSUE TITLE
How to use VotingClassifier in braindecode with EEGClassifier?

### ISSUE THREAD

**Issue by zinker8086** [braindecode/braindecode#192]
Hello, I want to use the VotingClassifer from sklearn to train my models together. I'm not sure because I use the BCI2014001, and it shows I just need to set the y=None in the EEGClassifier, but VotingClassifier need to input y. So how I can deal with that problem?
Thank you.
`eclf = VotingClassifier(estimators=[('a', clf), ('b', clf0), ('c', clf1)], voting='soft', weights=[1, 2, 2])`

**Comment by robintibor** [comment]
Uh sorry we missed this so far, will have a look

**Comment by bruAristimunha** [comment]
Hello @zinker8086 and @robintibor,

I know it's been a while, but the solution to this question is the code below:

```python
from sklearn.ensemble import VotingClassifier
from skorch.helper import SliceDataset


y_train = list(SliceDataset(train_set, 1))

eclf = VotingClassifier(estimators=[('a', models_list[0]),  ('b', models_list[1]), ('c',  models_list[2])], 
                        voting='soft', weights=[1, 2, 2])

eclf.fit(train_set, y_train)
```
