### ISSUE TITLE
The location of create_from_X_y has changed?

### ISSUE THREAD

**Issue by anbara** [braindecode/braindecode#193]
In issue #136, there is a problem with create_from_X_y, 
Maybe, has the script already been modified?
Document hasn't caught up with the fix yet.

https://braindecode.org/auto_examples/plot_custom_dataset_example.html#sphx-glr-auto-examples-plot-custom-dataset-example-py

Current document (I think wrong)
```
from braindecode.datautil import create_from_X_y
```

Correct
```
from braindecode.datasets import create_from_X_y
```

**Comment by agramfort** [comment]
@anbara the doc is built automatically based on current code in master branch. We need to add to the doc the difference between stable and dev versions.
