### ISSUE TITLE
create_windows_from_events documentation error

### ISSUE THREAD

**Issue by gifale95** [braindecode/braindecode#194]
It seems to me that there is a mistake in the documentation of the function *braindecode.datautil.create_windows_from_events*:
https://braindecode.org/generated/braindecode.datautil.create_windows_from_events.html#braindecode.datautil.create_windows_from_events

The documentation string of the parameter *drop_last_window* of such function starts with "*If **True**, an additional overlapping window...*", whereas is should be saying "*If **False**, ad additional overlapping window...*".

![pic](https://user-images.githubusercontent.com/50326481/111445492-be2de180-870b-11eb-8b79-9662bba21374.png)

**Comment by agramfort** [comment]
any chance you can open a PR? thanks a lot
