### ISSUE TITLE
Installation, MOABB

### ISSUE THREAD

**Issue by OleAd** [braindecode/braindecode#196]
Not quite sure what is going on over at MOABB, but the current version of their repository is missing the file requirements.txt. This makes installing MOABB a bit of a hassle, and the code snippet under section 2 of the installation paragraph (see below) will not work.

"Install MOABB from https://github.com/NeuroTechX/moabb, needed if you want to use MOABB datasets utilities:"
```
pip install download
python -c "from download import download; download('https://raw.githubusercontent.com/NeuroTechX/moabb/master/requirements.txt', 'requirements.txt', replace=True)"
pip install -r requirements.txt
rm requirements.txt
pip install -U https://github.com/NeuroTechX/moabb/archive/master.zip
```

**Comment by OleAd** [comment]
See [this related issue](https://github.com/NeuroTechX/moabb/issues/162) for information. I believe this can be closed once MOABB is on pypi, and the installation documentation is updated.

**Comment by agramfort** [comment]
I would consider allowing something like

pip install moabb[full]

which would be an install option to install all dependencies

cc @sylvchev

**Comment by sylvchev** [comment]
Please, let us know if there is problem with this release. Sorry for the downtime period, now that poetry is fully setup up, update should be easier.

**Comment by sylvchev** [comment]
Yes
I made some tests on all examples that include MOABB in the `examples/` dir. I got one error regarding the plots, because of the wrong matplotlib backend (with Python 3.9 and QT5 on OS X). I don't think it is related, because when switching to another backend, everything run smoothly.

I could open a PR to update the README, the environment/requirements files and the CI, as now moabb could be handle as any regular dependency.

**Comment by agramfort** [comment]
if you can open a PR it's great.

thx !

>

**Comment by robintibor** [comment]
sounds great. Also note this related PR https://github.com/braindecode/braindecode/issues/196 in order to get CI to run (don't quite understand if this activity here has any effect on us: https://github.com/conda-forge/torchvision-feedstock/pull/21)

**Comment by ErikBjare** [comment]
@agramfort PR opened, see #201.
