### ISSUE TITLE
EEGResNet with `final_pool_length='auto'`

### ISSUE THREAD

**Issue by alamie** [braindecode/braindecode#220]
I tried to use the `EEGResNet` as follows:

```python
import torch
from braindecode.models.eegresnet import EEGResNet

n_channels, n_times = 8, 4096

model = EEGResNet(in_chans=n_channels,
                  n_classes=1,
                  input_window_samples=n_times,
                  final_pool_length='auto',
                  n_first_filters=2)

inp = torch.rand((1, n_channels, n_times, 1))
out = model(inp)
```

But this code gives me the following error:
```
RuntimeError: Calculated padded input size per channel: (4096 x 1). Kernel size: (262081 x 1). Kernel size can't be greater than actual input size
```

I tried to increate the value of `n_times` but it does not help. Except for `final_pool_length='auto'`, everything is similar to [`test_eegresnet`](https://github.com/braindecode/braindecode/blob/41d6fc4479b8a3b7db443648d288e47981be29b1/test/unit_tests/models/test_models.py#L62). 

Is this behavior to be expected?

**Comment by sliwy** [comment]
This is not an expected behavior. `EEGResNet` model does not work with `final_pool_length='auto'` at the moment.

I think the reason for that is the dilation parameter (`cur_dilation`) passed to the `AvgPool2dWithConv`
```python
self.add_module('mean_pool', AvgPool2dWithConv(
(self.final_pool_length, 1), (1, 1), dilation=(int(cur_dilation[0]),(cur_dilation[1]))))
```
You can find a possible fix (to be confirmed with @robintibor) and more details in the https://github.com/braindecode/braindecode/pull/221

**Comment by alamie** [comment]
@sliwy I agree with you and think that the `dilation` parameter is the problem here. In my example, the `AvgPool2dWithConv` layer will receive a feature map with shape `(C, 4096, 1)`. Say that we have `dilation=(64, 1)` ; the forward pass of `AvgPool2dWithConv` expects a very "tall" input (the height of the input tensor must be strictly larger than 64 * (4096 - 1) for the dilation to make sense). It works if you set `dilation = (1, 1)`: you will pool a feature map from `(C, 4096, 1)` to `(C, 1, 1)`. 

As it is, `AvgPool2dWithConv` currently relies on a `Conv2d` layer to do the pooling. However, the weight tensor of this convolution is fixed (it's a tensor full of 1s). Therefore, I'm not sure there's any benefit from using a `Conv2d` layer (with depthwise convolution) here. IMHO, `AdaptiveAvgPool2d((1, 1))` might do the job as well.

**Comment by sliwy** [comment]
@alamie thanks for your explanation. In the PR #221 I implemented almost the same as you suggested with standard `AvgPool2D` just to be consistent with the scenario when we explicitly specify `final_pool_length`.

**Comment by robintibor** [comment]
So should be fixed now, you can have a try @alamie , thanks for creating the issue!
