### ISSUE TITLE
Error to import SleepPhysionet

### ISSUE THREAD

**Issue by bruAristimunha** [braindecode/braindecode#227]
When a try import SleepPhysionet from braindecode.datasets.sleep_physionet I get an import error.

It seems to me that this line is missing in __init__ from datasets

`from .sleep_physionet import SleepPhysionet`

**Comment by hubertjb** [comment]
Thanks for pointing out the issue @bruAristimunha ! This will actually be fixed by #213, along with the inclusion of `SleepPhysionet` in the documentation.

**Comment by bruAristimunha** [comment]
Thanks for the feedback! I'll wait and close PR and Issue.
