### ISSUE TITLE
Test for  TUH Base Dataset labels

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#235]
https://github.com/braindecode/braindecode/pull/218/files is untested, we add labels to base datasets. In the test we would need to mock out parts of the TUH dataset so the test runs without TUH data being available.

**Comment by gemeinl** [comment]
As with https://github.com/braindecode/braindecode/pull/267/files, BaseDataset.target does not exist anymore / is not used anymore. Target is now a dynamic lookup in BaseDataset.description[BaseDataset.target_name] in `__getitem__`. This might be slow, however, we never use base datasets for decoding / never actually call its `__getitem__`. Setting description is tested, so there is no need for another test. However, TUH Abnormal code needs to be updated after / with PR 267.
