### ISSUE TITLE
Align windowing functions argument names

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#246]
Although technically correct, `create_windows_from_events` accepts `trial_start_offset_samples` and `trial_stop_offset_samples` whereas `create_fixed_length_windows` accepts `start_offset_samples` and `stop_offset_samples`, since no trials exist.
This might be confusing to users or it could complicate switching from one task to another. Maybe both functions could just accept `start_offset_samples` and `stop_offset_samples`.

**Comment by dcwil** [comment]
@vytjan, @Ann-KathrinKiessner, @HenrikBons & I are working on this
