### ISSUE TITLE
Multiversion Sphinx

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#250]
We would like to have a toggle button to switch between master and other versions like mne has https://mne.tools 
As suggested in https://github.com/braindecode/braindecode/pull/248 , we could use sphinx-multiversion:

> have a look at
https://holzhaus.github.io/sphinx-multiversion/master/index.html
it's used here for example:
https://github.com/mne-tools/mne-nirs/blob/master/doc/conf.py#L49

Right now our Github Action deploys the docs from the master branch to a subdirectory master:
https://github.com/braindecode/braindecode/blob/364bd331f522f5ce18ef3b50781dfbf105882358/.github/workflows/tests-and-docs.yml#L81

This was done to prevent that the stable/last-release docs are being overriden, which caused quite some confusion in users before.
We now would want a proper setup where older docs still exist and can be seen through the toggle button, the default on braindecode.org should be the last release docs. If you build locally, the default might better be the docs from current code.

**Comment by bruAristimunha** [comment]
Related with #272.
