### ISSUE TITLE
`plot_load_save_datasets.py` leaves artifacts in examples directory

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#252]
The `plot_load_save_datasets.py` stores `0-epo.fif`, `1-epo.fif` and `description.json` in the examples directory, which causes an error in all `make html` runs after the very first.

**Comment by robintibor** [comment]
ah that's why! :D

**Comment by gemeinl** [comment]
Can potentially be solved by writing to a temporary directory using tempfile.

**Comment by agramfort** [comment]
I bumped into this issue in
https://github.com/braindecode/braindecode/pull/258
and I fixed it with a tempdir

>

**Comment by robintibor** [comment]
yap great so can be closed
