### ISSUE TITLE
Remove `start_offset_samples` and `stop_offset_samples` argument in `create_fixed_length_windows`

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#269]
Instead or renaming the arguments as discussed in https://github.com/braindecode/braindecode/pull/260, we realized that these arguments do not make sense at all in the setting of `create_fixed_length_windows`. There, these arguments are equivalent to applying a preprocessing step that crops the signals in advance. We hence aim to remove the arguments at some point and deprecate them for now.

**Comment by dcwil** [comment]
#273
