### ISSUE TITLE
CodeCov broken

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#271]
at the moment seems CodeCov is broken? Looks to me as if it is broken since the move from Travis to Github Actions?
![image](https://user-images.githubusercontent.com/1178948/123125682-0403ef80-d449-11eb-87a6-0cfa26fb2639.png)
This is what we see at the moment when looking at individual commits to master on CodeCov:
![image](https://user-images.githubusercontent.com/1178948/123125744-15e59280-d449-11eb-82ef-38764bb35481.png)

Although workflow part https://github.com/braindecode/braindecode/actions/runs/963637851/workflow#L49-L58 seems to run fine?

https://github.com/braindecode/braindecode/blob/8f6f1406d85a0412f480662f07595ddeaca4d869/.github/workflows/tests-and-docs.yml#L54-L58 

![Screenshot 2021-06-23 at 17-33-55 Build software better, together](https://user-images.githubusercontent.com/1178948/123126032-580ed400-d449-11eb-8b1f-8478be377fc4.png)
![Screenshot 2021-06-23 at 17-34-09 Build software better, together](https://user-images.githubusercontent.com/1178948/123126043-59d89780-d449-11eb-9440-6479ed20617d.png)

https://github.com/braindecode/braindecode/runs/2893037704?check_suite_focus=true (See Upload Coverage to CodeCov)

Do you have any ideas what could be the problem @agramfort ?

**Comment by agramfort** [comment]
I could look tomorrow

>

**Comment by robintibor** [comment]
yes I don't consider it urgent, was more considering maybe you know a typical reason already. Since not, I can also check myself after the sprint.

**Comment by robintibor** [comment]
CodeCov report:
https://gist.github.com/robintibor/e9d5276defb5606f728748b03159dd8b

**Comment by robintibor** [comment]
had to explicitly specify coverage format, now codecov is working again @agramfort
