### ISSUE TITLE
Incorrect import in example

### ISSUE THREAD

**Issue by philipollaswilson** [braindecode/braindecode#283]
https://braindecode.org/auto_examples/plot_custom_dataset_example.html

It should be:
 from braindecode.datasets import create_from_X_y

not:
from braindecode.datautil import create_from_X_y

**Comment by robintibor** [comment]
HI @philipollaswilson thanks for the issue, we now show the documentation for the last release on https://braindecode.org, it seems you are using the current master? then the documentation is under https://braindecode.org/master/ .
We are working on having a proper multi version button in https://github.com/braindecode/braindecode/issues/250

**Comment by bruAristimunha** [comment]
Hi @philipollaswilson,

Can we close this issue at this moment? A new version of the documentation will address this point. PR #272

**Comment by philipollaswilson** [comment]
Yup!

Sent from Proton Mail mobile

-------- Original Message --------
