### ISSUE TITLE
results published in reseearch paper:  Aret

### ISSUE THREAD

**Issue by bokey007** [braindecode/braindecode#300]
results published in the research paper:  Are these results obtained by training ConvNet on all subjects are single subject only.

Research paper: "Deep learning with convolutional neural networks for EEG Decoding and Visualization"

If ConvNet is trained on all subjects then how do we fetch data od all the subjects with MOABBDataset

**Comment by gemeinl** [comment]
Results are within subject, so train on train data of __one__ subject and evaluate on the test data of __the same__ subject.
Please correct me, if I am mistaken @robintibor .
If you still want to download data of all subjects, try initializing the dataset with `subject_ids=None`. This will download data of all subjects to `~/mne_data/` and return it. Please note that this will take some time.

**Comment by robintibor** [comment]
As @gemeinl wrote, the results are within subject, so we always train on one subject, test on the same. We repeat this for all subjects and then average across subjects. So we never train on all subjects together in that paper.

**Comment by bokey007** [comment]
Thanks for the reply.

Is there any way to extend this model across all subjects? (maybe quite useful in real-time analysis or classification )

**Comment by robintibor** [comment]
You could just do it, i.e., you could just load all subjects, concatenate the datasets and train on them
