### ISSUE TITLE
what does this signify -- >  trial_stop_offset_samples 

### ISSUE THREAD

**Issue by bokey007** [braindecode/braindecode#305]
trial_stop_offset_samples

does the above signify that we end the trial at the event trigger?

Hi, I am new to EEG. I was wondering how the trails are created in the first place 

```
windows_dataset  = create_windows_from_events(
    dataset,
    trial_start_offset_samples = trial_start_offset_samples,
    trial_stop_offset_samples =0,
    window_size_samples=input_window_samples,
    window_stride_samples=n_preds_per_input,
    drop_last_window=False,
    preload=True,
    )
```
What does "trial_stop_offset_samples "  indicate in the above code? are we not taking the data after event trigger ?

**Comment by robintibor** [comment]
So here we assume the data has start and stop markers for the trials. For example, for a 4-second trial starting at second 10, a start marker at second 10 and a stop marker at second 14. Now for decoding, you might just take exactly these 4 seconds to decode the trial label. Then you would use `trial_start_offset_samples=0` `trial_stop_offset_samples=0`. But you might also want to use a little bit more or less at the start or the end of the trial. Like let's assume you want also 10 samples before and 20 samples after the start and stop marker, then you would use `trial_start_offset_samples=-10` `trial_stop_offset_samples=20`. The unit here is in sample recordings so you would have to know the sampling rate to determine these numbers.

**Comment by robintibor** [comment]
Also see the explanation in the docstring:

https://github.com/braindecode/braindecode/blob/c20100c5a4195adf40d3c2644f16116868fd888f/braindecode/preprocessing/windowers.py#L32-L58

**Comment by bokey007** [comment]
@robintibor --> thank you so much ... makes sense 

I should join as intern for you  ---> would learn a lot LOL

Thanks,
bokey
