### ISSUE TITLE
i need to define my own pytorch model. Can I subclass it from nn.module 

### ISSUE THREAD

**Issue by bokey007** [braindecode/braindecode#307]
Hello,

I need to define my own py-torch model.

Can I subclass it from nn.module ?

or I need to subclass it from nn.sequential as done in all the models of brain decode ?

**Comment by robintibor** [comment]
Yes it is totally fine to subclass from nn.Module. Only `to_dense_prediction_model` makes very specific assumptions about the model, so as long as you don't need that you should be fine. This function is only needed if you want to do cropped decoding and therefore need per-timestep outputs, but your original model has stride in pooling or conv layers and therefore does not have outputs for each timestep

**Comment by bokey007** [comment]
@robintibor 

 Thanks for the reply

and its a wonderful project
