### ISSUE TITLE
what is the input dimension to the DeepConvNet

### ISSUE THREAD

**Issue by hzhz2020** [braindecode/braindecode#323]
https://github.com/braindecode/braindecode/blob/2dbd40cc7951934ad32892770536e360b6188920/braindecode/models/deep4.py#L114

Dear Authors 

Thanks for your cool works!
I have a question about the DeepConvNet architecture. In your code deep4.py, the kernel_size of the temporal convolution is (self.filter_time_length, 1). But in the paper you mentioned that **"we represent the input as a 2D-array with the number of time steps as width and the number of electrodes as the height"**.  Shouldn't the kernel size be **(1, self.filter_time_length)** then?

**Comment by robintibor** [comment]
in the code at that point, the input is in dimension ordering batch x 1 x time x EEG channels, and kernel with `(self.filter_time_length, 1), ` is therefore a kernel applied with `filter_time_length` on each EEG channel separately... the naming in the paper with regard to width/height is maybe a bit inconsistent with how pytorch images are usually fed in... maybe just ignore which dimension we call "width" and which we call "height"  in paper, it is more for illustrative purposes.
