### ISSUE TITLE
Error thrown in Colab due to not supported comparison

### ISSUE THREAD

**Issue by robert-DL** [braindecode/braindecode#369]
Hi all, 

I was trying to prepare an interactive tutorial for Braindecode and MNE. It is intended to use Colab for easy GPU access. When I try to run the basic tutorial from the braindecode page (Trialwise Decoding on BCIC IV 2a Dataset), I am getting the error message below. I do not have this problem in PyCharm. From the errors thrown I can not say if it is a problem with braindecode or MNE. 

Best 
Robert 
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-4398e75d2d71> in <module>()
     18 )
     19 
---> 20 clf.fit(train_set, y=None, epochs=n_epochs)

8 frames
/usr/local/lib/python3.7/dist-packages/skorch/classifier.py in fit(self, X, y, **fit_params)
    139         # this is actually a pylint bug:
    140         # https://github.com/PyCQA/pylint/issues/1085
--> 141         return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
    142 
    143     def predict_proba(self, X):

/usr/local/lib/python3.7/dist-packages/skorch/net.py in fit(self, X, y, **fit_params)
   1213             self.initialize()
   1214 
-> 1215         self.partial_fit(X, y, **fit_params)
   1216         return self
   1217 

/usr/local/lib/python3.7/dist-packages/skorch/net.py in partial_fit(self, X, y, classes, **fit_params)
   1172         self.notify('on_train_begin', X=X, y=y)
   1173         try:
-> 1174             self.fit_loop(X, y, **fit_params)
   1175         except KeyboardInterrupt:
   1176             pass

/usr/local/lib/python3.7/dist-packages/skorch/net.py in fit_loop(self, X, y, epochs, **fit_params)
   1091                                   step_fn=self.validation_step, **fit_params)
   1092 
-> 1093             self.notify("on_epoch_end", **on_epoch_kwargs)
   1094         return self
   1095 

/usr/local/lib/python3.7/dist-packages/skorch/net.py in notify(self, method_name, **cb_kwargs)
    357         getattr(self, method_name)(self, **cb_kwargs)
    358         for _, cb in self.callbacks_:
--> 359             getattr(cb, method_name)(self, **cb_kwargs)
    360 
    361     # pylint: disable=unused-argument

/usr/local/lib/python3.7/dist-packages/braindecode/training/scoring.py in on_epoch_end(self, net, dataset_train, dataset_valid, **kwargs)
    356                 batch_X, batch_y = unpack_data(batch)
    357                 # TODO: remove after skorch 0.10 release
--> 358                 if not check_version('skorch', min_version='0.10.1'):
    359                     yp = net.evaluation_step(batch_X, training=False)
    360                 # X, y unpacking has been pushed downstream in skorch 0.10

/usr/local/lib/python3.7/dist-packages/mne/utils/check.py in check_version(library, min_version)
     90     else:
     91         if min_version and \
---> 92                 LooseVersion(library.__version__) < LooseVersion(min_version):
     93             ok = False
     94     return ok

/usr/lib/python3.7/distutils/version.py in __lt__(self, other)
     50 
     51     def __lt__(self, other):
---> 52         c = self._cmp(other)
     53         if c is NotImplemented:
     54             return c

/usr/lib/python3.7/distutils/version.py in _cmp(self, other)
    335         if self.version == other.version:
    336             return 0
--> 337         if self.version < other.version:
    338             return -1
    339         if self.version > other.version:

TypeError: '<' not supported between instances of 'str' and 'int'
`

**Comment by agramfort** [comment]
can you share a full code snippet to replicate and report the versions you
use for mne and braindecode?

>

**Comment by robert-DL** [comment]
Sure! I removed all that ipy widget stuff I coded since it isn't causing trouble. In the end, we have the tutorial from the webpage again. Maybe I have to install mne from the github repo, I will try this and report if it worked. 
`
!pip install mne
!pip install git+https://github.com/braindecode/braindecode.git
!pip install moabb

import copy

# Widgets
#from ipywidgets import interact, interactive, fixed, interact_manual
#import ipywidgets as widgets

# Plotting
import matplotlib.pyplot as plt, random

# Numpy as helper
import numpy as np

# mne
import mne

# PyTorch
import torch

# Skorch Utils
from skorch.callbacks import LRScheduler
from skorch.helper import predefined_split

# Loading datasets. MOABB is special, for now sets use MNE/ NUMPY
from braindecode.datasets.moabb import MOABBDataset

# Preprocessing
from braindecode.preprocessing.preprocess import \
    (exponential_moving_standardize, preprocess, Preprocessor)

# Events are given, we want to get windows out as an input to the network
from braindecode.preprocessing.windowers import create_windows_from_events

# MNE UTILS
import mne

# Loading datasets. MOABB is special, for now sets use MNE/ NUMPY
from braindecode.datasets.moabb import MOABBDataset

# Preprocessing
from braindecode.preprocessing.preprocess import exponential_moving_standardize, preprocess, Preprocessor

# Events are given, we want to get windows out as an input to the network
from braindecode.preprocessing.windowers import create_windows_from_events

# Utils and models
from braindecode.util import set_random_seeds
from braindecode.models import ShallowFBCSPNet
from braindecode import EEGClassifier

# Choose one or multiple subjects 
subject_ids = [1]

dataset = MOABBDataset(dataset_name="BNCI2014001", subject_ids=subject_ids) 

# ------------------------------ Preprocessing ------------------------------- #
low_cut_hz = 4.  # Frequency band in the low regime to cut (below 4hz)
high_cut_hz = 38.  # Frequency band in the high regime to cut (over 38hz)

# Factor Exponential moving standardization
factor_new = 1e-3
init_block_size = 1000

# Show Channels before preprocessing
steps = []

preprocessors = [
    Preprocessor('pick_types', eeg=True, meg=False, stim=False),  # Keep EEG sensors, remove the rest
    Preprocessor(lambda x: x * 1e6),  # convert to uV
    Preprocessor('filter', l_freq=low_cut_hz, h_freq=high_cut_hz),
    Preprocessor(exponential_moving_standardize, factor_new=factor_new,
                 init_block_size=init_block_size)
]

preprocess(dataset, preprocessors)

# ------------------------------- Windowing ---------------------------------- #

trial_start_offset_seconds = -0.5
sfreq = dataset.datasets[0].raw.info["sfreq"]  # Sampling frequency sample 1
assert all([ds.raw.info["sfreq"] == sfreq for ds in dataset.datasets])

# Calculate the trial start offset in samples
trial_start_offset_samples = int(trial_start_offset_seconds * sfreq)
windows_dataset = create_windows_from_events(
    dataset,
    trial_start_offset_samples=trial_start_offset_samples,
    trial_stop_offset_samples=0,
    preload=True
)

# ---------------------------- TRAIN/VAL - SPLIT ----------------------------- #
splitted = windows_dataset.split('session')
train_set = splitted['session_T']
valid_set = splitted['session_E']

"""### Model"""

# Check if GPU is available and set it 
cuda = torch.cuda.is_available()
device = 'cuda' if cuda else 'cpu'
if cuda:
    torch.backends.cudnn.benchmark = True

seed = 20200220  # random seed for reproducible results
set_random_seeds(seed=seed, cuda=cuda)

# The model is created in such a way that the last layer knows how many
# classes exist, how many input channels (convolutional neural network)
n_classes = 4
n_chans = train_set[0][0].shape[0]
input_window_samples = train_set[0][0].shape[1]

# in torch one needs to specify the number of inputs for a linear layer, for that
# reason the output size of the conv. layers has to be known --> final conv length, auto
model = ShallowFBCSPNet(n_chans, n_classes,
                        input_window_samples=input_window_samples,
                        final_conv_length='auto'  
                        )

# Send model to GPU
if cuda:
    model.cuda()

"""### Training"""

lr = 1e-5 * 6.25  # learning rate
weight_decay = 0 
batch_size = 64  
n_epochs = 100

clf = EEGClassifier(
    model,
    criterion=torch.nn.NLLLoss,
    optimizer=torch.optim.AdamW,
    train_split=predefined_split(valid_set),
    optimizer__lr=lr,
    optimizer__weight_decay=weight_decay,
    batch_size=batch_size,
    callbacks=["accuracy",
               ("lr_scheduler", LRScheduler('CosineAnnealingLR', T_max=n_epochs - 1))
               ],
    device=device,
)

clf.fit(train_set, y=None, epochs=n_epochs)
`
