### ISSUE TITLE
Naming of models

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#37]
Rename Deep4Net -> Deep4Model, ShallowFBCSPNet -> ShallowFBCSPModel

And/But: EEGNet ->EEGNetModel

**Comment by agramfort** [comment]
I would not do this as it's already imported from braindecode.models so it's already clear that they are models

**Comment by robintibor** [comment]
ok, so let's rephrase, check naming of current models, also check back with @TonioBall
