### ISSUE TITLE
ModuleNotFoundError: No module named 'braindecode.datautil.signal_target' :Braindecode 0.6

### ISSUE THREAD

**Issue by fawaz2015** [braindecode/braindecode#372]
Hello dears, I made an env using conda on Windows 10
conda create --name t_brain python=3.7 
Then i install torch and braindecode by the following instructions in the official braindecode website, https://braindecode.org/   using pip

everything working fine, except braindecode
when I try to import SignalAndTarget ( from braindecode.datautil.signal_target import SignalAndTarget ), it started to work but the error occurred.
2022-01-04 03:10:50,305 INFO : Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-01-04 03:10:50,308 INFO : NumExpr defaulting to 8 threads.

ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_22956/1653306546.py in <module>
----> 1 from braindecode.datautil.signal_target import SignalAndTarget

ModuleNotFoundError: No module named 'braindecode.datautil.signal_target'

I deleted the entire env and again installed everything but the same error.
I also tried to install braindecode via conda , however, I couldn't, due to another error :
0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Timed out. 
Here are all the packages in env:
# packages in environment at C:\Users\lenovo\miniconda3\envs\t_brain:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.4                    pypi_0
argcomplete               1.12.3             pyhd3eb1b0_0
argon2-cffi               20.1.0           py37h2bbff1b_1
async_generator           1.10             py37h28b3542_0
attrs                     21.2.0             pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
bayesian-optimization     1.2.0                    pypi_0
blas                      1.0                         mkl
bleach                    4.0.0              pyhd3eb1b0_0
boto3                     1.18.21            pyhd3eb1b0_0
botocore                  1.21.41            pyhd3eb1b0_1
bottleneck                1.3.2            py37h2a96729_1
braindecode               0.6                      pypi_0
brotli                    1.0.9                ha925a31_2
brotlipy                  0.7.0           py37h2bbff1b_1003
ca-certificates           2021.10.8            h5b45459_0
cached-property           1.5.2                      py_0
certifi                   2021.10.8        py37h03978a9_1
cffi                      1.15.0           py37h2bbff1b_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.3              pyhd3eb1b0_0
cloudpickle               2.0.0                    pypi_0
colorama                  0.4.4              pyhd3eb1b0_0
cryptography              36.0.0           py37h21b164f_0
cudatoolkit               11.3.1               h59b6b97_2
cycler                    0.11.0             pyhd3eb1b0_0
dataclasses               0.8                pyh6d0b6a4_7
debugpy                   1.5.1            py37hd77b12b_0
decorator                 5.1.0              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
einops                    0.3.2                    pypi_0
entrypoints               0.3                      py37_0
flask                     2.0.2              pyhd3eb1b0_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
gym                       0.21.0                   pypi_0
h5py                      3.6.0            py37h3de5c98_0
hdf5                      1.10.6               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      3.3                pyhd3eb1b0_0
importlib-metadata        4.8.2            py37haa95532_0
importlib_metadata        4.8.2                hd3eb1b0_0
intel-openmp              2021.4.0          haa95532_3556
ipykernel                 6.4.1            py37haa95532_1
ipython                   7.29.0           py37hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.5              pyhd3eb1b0_1
itsdangerous              2.0.1              pyhd3eb1b0_0
jedi                      0.18.0           py37haa95532_1
jinja2                    3.0.2              pyhd3eb1b0_0
jmespath                  0.10.0             pyhd3eb1b0_0
joblib                    1.1.0              pyhd3eb1b0_0
jpeg                      9d                   h2bbff1b_0
jsonschema                3.2.0              pyhd3eb1b0_2
jupyter                   1.0.0                    py37_7
jupyter_client            7.1.0              pyhd3eb1b0_0
jupyter_console           6.4.0              pyhd3eb1b0_0
jupyter_core              4.9.1            py37haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
kaggle                    1.5.12                   pypi_0
kiwisolver                1.3.1            py37hd77b12b_0
libiconv                  1.15                 h1df5818_7
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.2.0                hd0e1b90_0
libuv                     1.40.0               he774522_0
libwebp                   1.2.0                h2bbff1b_0
libxml2                   2.9.12               h0ad7f3c_0
libxslt                   1.1.34               he774522_0
lxml                      4.7.1            py37h1985fb9_1
lz4-c                     1.9.3                h2bbff1b_1
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                2.0.1            py37h2bbff1b_0
matplotlib                3.5.0            py37haa95532_0
matplotlib-base           3.5.0            py37h6214cd6_0
matplotlib-inline         0.1.2              pyhd3eb1b0_2
mistune                   0.8.4           py37hfa6e2cd_1001
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py37h2bbff1b_0
mkl_fft                   1.3.1            py37h277e83a_0
mkl_random                1.2.2            py37hf11a4ad_0
mne                       0.24.1                   pypi_0
msys2-conda-epoch         20160418                      1
munkres                   1.1.4                      py_0
nb_conda                  2.2.1                    py37_0
nb_conda_kernels          2.3.1            py37haa95532_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.1.0            py37haa95532_0
nbformat                  5.1.3              pyhd3eb1b0_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
notebook                  6.4.6            py37haa95532_0
numexpr                   2.8.1            py37hb80d3ca_0
numpy                     1.21.2           py37hfca59bb_0
numpy-base                1.21.2           py37h0829f74_0
olefile                   0.46                     py37_0
openssl                   1.1.1l               h8ffe710_0
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.3.4            py37h6214cd6_0
pandas-datareader         0.10.0             pyhd3eb1b0_0
pandocfilters             1.4.3            py37haa95532_1
parso                     0.8.2              pyhd3eb1b0_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.4.0            py37hd45dc43_0
pip                       21.2.4           py37haa95532_0
pooch                     1.5.2                    pypi_0
prometheus_client         0.12.0             pyhd3eb1b0_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
prompt_toolkit            3.0.20               hd3eb1b0_0
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.10.0             pyhd3eb1b0_0
pyopenssl                 21.0.0             pyhd3eb1b0_1
pyparsing                 3.0.4              pyhd3eb1b0_0
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.18.0           py37h196d8e1_0
pysocks                   1.7.1                    py37_1
python                    3.7.11               h6244533_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-slugify            5.0.2                    pypi_0
python_abi                3.7                     2_cp37m
pytorch                   1.10.1          py3.7_cuda11.3_cudnn8_0
pytorch-model-summary     0.1.1                      py_0
pytorch-mutex             1.0                        cuda
pytz                      2021.3             pyhd3eb1b0_0
pywin32                   302              py37h827c3e9_1
pywinpty                  0.5.7                    py37_0
pyyaml                    6.0              py37h2bbff1b_1
pyzmq                     19.0.2                   pypi_0
qt                        5.9.7            vc14h73c81de_0
qtconsole                 5.1.1              pyhd3eb1b0_0
qtpy                      1.10.0             pyhd3eb1b0_0
requests                  2.26.0             pyhd3eb1b0_0
s3transfer                0.5.0              pyhd3eb1b0_0
scikit-learn              1.0.1            py37hf11a4ad_0
scipy                     1.7.1            py37hbe87c03_2
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                58.0.4           py37haa95532_0
sip                       4.19.8           py37h6538335_0
six                       1.16.0             pyhd3eb1b0_0
skorch                    0.11.0                   pypi_0
sqlite                    3.37.0               h2bbff1b_0
tabulate                  0.8.9                    pypi_0
terminado                 0.9.4            py37haa95532_0
testpath                  0.5.0              pyhd3eb1b0_0
text-unidecode            1.3                      pypi_0
threadpoolctl             2.2.0              pyh0d69192_0
tk                        8.6.11               h2bbff1b_0
torchsummary              1.5.1                    pypi_0
tornado                   6.1              py37h2bbff1b_0
tqdm                      4.62.3             pyhd3eb1b0_1
traitlets                 5.1.1              pyhd3eb1b0_0
typing_extensions         3.10.0.2           pyh06a4308_0
urllib3                   1.26.7             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1                    py37_1
werkzeug                  2.0.2              pyhd3eb1b0_0
wheel                     0.37.0             pyhd3eb1b0_1
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0            py37haa95532_0
wincertstore              0.2              py37haa95532_2
winpty                    0.4.3                         4
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
zipp                      3.6.0              pyhd3eb1b0_0
zlib                      1.2.11               h8cc25b3_4
zstd                      1.4.9                h19a0ad4_0

**Comment by robintibor** [comment]
Hi,
SignalAndTarget no longer exists for quite some time I think, do you have some specific need for it?

**Comment by fawaz2015** [comment]
> Hi, SignalAndTarget no longer exists for quite some time I think, do you have some specific need for it?

oh, thank you dear
Yes, but it's not a problem, I'll handle it. The problem is that there is no clear updated documentation about the deleted and added functions.
If you have a link about the features added and deleted, I would be grateful. Thank you

**Comment by robintibor** [comment]
Basically, Version 0.5 was a major rewrite, changes since then are under https://braindecode.org/whats_new.html

But if you used something prior to 0.5, then you should be aware many things have changed, and check documentation at braindecode.org for how things currently work.

**Comment by fawaz2015** [comment]
> Basically, Version 0.5 was a major rewrite, changes since then are under https://braindecode.org/whats_new.html
> 
> But if you used something prior to 0.5, then you should be aware many things have changed, and check documentation at braindecode.org for how things currently work.

thank you dear
