### ISSUE TITLE
Using ShallowFBCSPNet with create_from_X_y

### ISSUE THREAD

**Issue by mxmlnbndsmnn** [braindecode/braindecode#373]
Hello there! I followed the steps described in the [trialwise decoding example](https://braindecode.org/auto_examples/plot_bcic_iv_2a_moabb_trial.html) and tried to adapt the process to work with a different dataset. Namely the 5 finger MI from [this dataset](https://figshare.com/collections/A_large_electroencephalographic_motor_imagery_dataset_for_electroencephalographic_brain_computer_interfaces/3917698?q=5F).

However, I seem to struggle with setting the parameters properly.
What I did is...
I load eeg data from a .mat file and also extract the events:
```
eeg_data.shape
Out: (736600, 22)
```
-> 22 Channels
Then I extract trial data + labels and create X and y as numpy arrays:
```
X.shape
Out: (957, 22, 240)
X[0].shape
Out: (22, 240)
y[0]
Out: 4
```
Split the dataset:
```
num_trials = len(X)
split_i = int(num_trials * 0.8)

train_X = X[:split_i]
valid_X = X[split_i:]
train_y = y[:split_i]
valid_y = y[split_i:]
```
Use create_from_X_y:
```
train_set = create_from_X_y(train_X, train_y, drop_last_window=False, sfreq=sample_frequency)
valid_set = create_from_X_y(valid_X, valid_y, drop_last_window=False, sfreq=sample_frequency)
```
(sample_frequency is 200)
Train set description:
```
     target
0         4
1         2
2         5
3         1
4         5
..      ...
760       3
761       1
762       1
763       5
764       5

[765 rows x 1 columns]
```
Valid set description:
```
     target
0         1
1         4
2         3
3         4
4         2
..      ...
187       4
188       5
189       3
190       5
191       5

[192 rows x 1 columns]
```
Create the model:
```
input_window_samples = train_set[0][0].shape[1] # shape is (22,240)
model = ShallowFBCSPNet(
    len(ch_names), # number of channels
    5, # number of classes
    input_window_samples=1000,
    final_conv_length='auto',
)
```
Here I used either input_window_samples =1000 or the value obtained from the shape of a trial as written above.

And finally the classifier:
```
batch_size = 32
n_epochs = 10
clf = EEGClassifier(
    model,
    criterion=torch.nn.NLLLoss,
    optimizer=torch.optim.AdamW,
    train_split=predefined_split(valid_set),
    optimizer__lr=0.0625 * 0.01,
    optimizer__weight_decay=0,
    batch_size=batch_size,
    callbacks=[
        "accuracy", ("lr_scheduler", LRScheduler('CosineAnnealingLR', T_max=n_epochs - 1)),
    ],
    device=device,
)
clf.fit(train_set, y=None, epochs=n_epochs)
```
But I always fail when trying to clf.fit.
Using `input_window_samples = train_set[0][0].shape[1] = 240` I get
"IndexError: Target 5 is out of bounds." in torch/nn/functional.py nll_loss line 2532
or using `input_window_samples=1000` I get
"RuntimeError: Calculated padded input size per channel: (10 x 1). Kernel size: (61 x 1). Kernel size can't be greater than actual input size" in torch/nn/modules/conv.py _conv_forward line 442.

So even if one of these values is valid for input_window_samples, there is another thing that I am missing, though I have no idea where to look at. Are dimensions for eeg trials/labels wrong? Did I misunderstood the parameters? Any idea would be very much appreciated!
Cheers, Max

**Comment by gemeinl** [comment]
Hi Max,
sorry, the error message for the first error could be more elusive.
The targets are expected to start from 0, so please adjust accordingly.
Instead of having targets from 1 to 5, they should range from 0 to 4.
Let me know whether this fixes your problems.
