### ISSUE TITLE
Tests that ensure runtime and memory limits

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#386]
I would like to propose adding tests that ensure our code runs within an expected time frame.
I am thinking about our dataset classes, the windowers as well as runtime of a single training epoch.

I experienced now several times that code that was once fast now consumes a lot of time and memory.
I suppose this happened due to reasonable code changes that introduced a hidden overhead.
Every time, it takes a lot of effort to track down and profile what is causing these slowdowns and memory drains.

Opinions @robintibor @hubertjb @sliwy @agramfort ?

**Comment by agramfort** [comment]
CI can be pretty unstable to do proper time checks but it's worth trying.

**Comment by sliwy** [comment]
Maybe this can help https://github.com/CFMTech/pytest-monitor to print/save the CPU/RAM consumption after every CI run. It can keep history of different CI runs as well.

Indeed, it would require some tests to check the stability of our pipeline on CI runners before making it a mandatory step failing if changes increase the computational load.

Do we see a significant increase of CPU/RAM consumption even in tests now or do we need a big dataset to see the problem?

**Comment by bruAristimunha** [comment]
I already improved the test in the last code sprint. It is 6 min rn
