### ISSUE TITLE
Getting ValueError when trying to run the examples 

### ISSUE THREAD

**Issue by ghazalehran** [braindecode/braindecode#394]
Hello,
I'm just trying to run the example codes to see how the library works. Basically, I am just copying the codes from https://braindecode.org/auto_examples/plot_bcic_iv_2a_moabb_trial.html in my notebook and run each step. However, when I try to run the Training[¶](https://braindecode.org/auto_examples/plot_bcic_iv_2a_moabb_trial.html#training) part, I get this error:

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/skorch/dataset.py](https://localhost:8080/#) in unpack_data(data)
     91     try:
---> 92         X, y = data
     93         return X, y

ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
8 frames
[/usr/local/lib/python3.7/dist-packages/skorch/dataset.py](https://localhost:8080/#) in unpack_data(data)
     95         # if a 1-tuple/list or something else like a torch tensor
     96         if not isinstance(data, (tuple, list)) or len(data) < 2:
---> 97             raise ValueError(ERROR_MSG_1_ITEM)
     98         raise ValueError(ERROR_MSG_MORE_THAN_2_ITEMS.format(len(data)))
     99 

ValueError: You are using a non-skorch dataset that returns 1 value. Remember that for skorch, Dataset.__getitem__ must return exactly 2 values, X and y (more info: https://skorch.readthedocs.io/en/stable/user/dataset.html).

**Comment by robintibor** [comment]
Cannot reproduce either when installing via pip or when installing via github master:
https://colab.research.google.com/drive/1letin_yKq1LLzrECEnWhZl3OsJ2OvW-l#scrollTo=1K_EydvWM_J3
https://colab.research.google.com/drive/1COd_kp7eGe8ZOOAaSKmIS7gOJqHwrqns#scrollTo=CFn0duIZM8XV

Do you still have this problem @ghazalehran ?

**Comment by ghazalehran** [comment]
Hi, It is solved, thanks for the help
