### ISSUE TITLE
 ImportError: cannot import name ‘Sequence‘ from ‘collections‘

### ISSUE THREAD

**Issue by Guan-Smile** [braindecode/braindecode#399]
Error:
File "G:\research\code\MicroDE_py\plot_bcic_iv_4_ecog_trial.py", line 262, in <module>
    from skorch.helper import predefined_split
  File "C:\Users\Lenovo\.conda\envs\braindecode\lib\site-packages\skorch\helper.py", line 6, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (C:\Users\Lenovo\.conda\envs\braindecode\lib\collections\__init__.py)

Solution:
Sequence should be imported from collections.abc instead of collections since Python 3.3. A warning is printed starting with Python 3.7 and in Python 3.9 the new import location will be required.( https://github.com/wireservice/agate/pull/737 )

So ` from collections import Sequence` should be:  ` from collections.abc import Sequence` since Python 3.10.

**Comment by agramfort** [comment]
This is an issue in Skorch not here. Are you using an up to date version of skorch?

**Comment by martinwimpff** [comment]
I recently ran into the same error and downgraded the python version of my environment to "solve" it.
Both times using the current 0.11 version. 
[Skorch fixed this issue](https://github.com/skorch-dev/skorch/pull/850) but they [haven't released it yet.](https://github.com/skorch-dev/skorch/issues/872)

**Comment by bruAristimunha** [comment]
Hello @Guan-Smile!

I was wondering, did the information given by @martinwimpff solve your issue?

**Comment by gbShaw** [comment]
I think this bug is caused by unsupported version of pytorch.  
the latest version of pytorch that skorch supported is 1.90, older than that in my pc.
The braindecode work perfect after pytorch=1.9 installed
