### ISSUE TITLE
Augmentation on GPU

### ISSUE THREAD

**Issue by martinwimpff** [braindecode/braindecode#404]
The Transforms of [AugmentedDataloader](https://github.com/braindecode/braindecode/blob/5a9208666bd2ebf99539ae1dab94c58bc56985d2/braindecode/augmentation/base.py#L153) currently use `X.device` to determine which device to use.
The problem with that is, that X/the dataset is often not on the GPU when getting passed to the Dataloader.
Therefore the augmentations would be processed on the CPU.

Changing [_make_collateable](https://github.com/braindecode/braindecode/blob/5a9208666bd2ebf99539ae1dab94c58bc56985d2/braindecode/augmentation/base.py#L145) from
```python
def _make_collateable(transform):
    def _collate_fn(batch):
        collated_batch = default_collate(batch)
        X, y = collated_batch[:2]
        return (*transform(X, y), *collated_batch[2:])
    return _collate_fn
```
to
```python
def _make_collateable(transform, device="cpu"):
    def _collate_fn(batch):
        collated_batch = default_collate(batch)
        X, y = collated_batch[:2]
        X = X.to(device)
        y = y.to(device)
        return (*transform(X, y), *collated_batch[2:])
    return _collate_fn
```
+adding the device Keyword to [AugmentedDataloader](https://github.com/braindecode/braindecode/blob/5a9208666bd2ebf99539ae1dab94c58bc56985d2/braindecode/augmentation/base.py#L153) would solve this problem.
What do you think about that @bruAristimunha ?

**Comment by bruAristimunha** [comment]
Hi @martinwimpff!

For me, looks nice to have this parameter control! But, I asked for the @cedricrommel review since he was responsible for this part of the code.

**Comment by bruAristimunha** [comment]
Hello @martinwimpff,

I created a PR to make it easier for @cedricrommel to review, could you take a look?

**Comment by martinwimpff** [comment]
@bruAristimunha looks fine for me 👍
