### ISSUE TITLE
Release v0.7

### ISSUE THREAD

**Issue by bruAristimunha** [braindecode/braindecode#410]
I had talked with Robin, but after much thought, I think this should be a public discussion with everyone involved in the library. Similar to the mne-tools.

It has been over a year since the last release. However, I'm still unsure if we have enough stuff for a new release. We have new documentation, new tutorials, some bugs fixed, and two new models, but no significant changes.

I have a proposal. What if we collect some open ideas from the issues, collect more ideas from the teams, and set a new milestone for the release? Something like:

1) One new contrastive model;
2) Implement a lazy approach as default;
3) Optimizing the workflow;
4) A new data visualization;

We can use a specific label for that, like version 0.7.

What do you think of this idea, @agramfort, @sliwy, @robintibor, @gemeinl, and @cedricrommel?

**Comment by bruAristimunha** [comment]
I set a milestone label on what I thought were good open issues/PR that could be closed. But we need to review that and create a more strategic issues list—thinking about how braindecode could change to increase the number of users.

https://github.com/braindecode/braindecode/milestone/1

**Comment by agramfort** [comment]
I think it's better to release early and release often. It's ok if
improvements and how massive. It shows
the project is alive and healthy !

**Comment by bruAristimunha** [comment]
cool, @agramfort, I think I agree with you.  So, to see if I understood correctly.  The idea is to close a 0.7 version, with what has already been done, release and take these ideas to a 0.8 version.  Is that the proposal?

**Comment by agramfort** [comment]
yes

**Comment by bruAristimunha** [comment]
Okay, thanks for the confirmation, I'll work on it.

**Comment by robintibor** [comment]
yes sounds good to me too

**Comment by bruAristimunha** [comment]
Closing issues https://github.com/braindecode/braindecode/pull/411, https://github.com/braindecode/braindecode/pull/413, I believe we can do the release (version 0.7).

For those who will deploy the new site version, I think it will be necessary to do it manually only the first time. Moving all the files to a folder called 0.6, and fix the [JSON](https://github.com/braindecode/braindecode/blob/master/docs/_static/versions.json) that maps the address. Someone more senior in the library has to do this. Can you please do @robintibor or @agramfort?

There are some possible improvements in the documentation, a button for dark mode, and optimising whitespace, but I think we can do it in version 0.8

Small gif :)
![new_braindecode](https://user-images.githubusercontent.com/42702466/193345778-4405b15b-6db5-4e9a-a6eb-54cbf9f9c9b8.gif)
unfortunately compressed to send here ;p

**Comment by agramfort** [comment]
@bruAristimunha I made you admin for https://github.com/braindecode/braindecode.github.io

**Comment by bruAristimunha** [comment]
😳 thank you very much for the trust, I will do my best to make everything work.

**Comment by bruAristimunha** [comment]
Hi @robintibor and @agramfort,

It's almost finished. I need permission in the PyPI, and make a text with the changes in the version. I want twitter a thread with small outlines, if possible.

https://braindecode.org/

Robin, can you give me permission to release it in the PyPI? 
I am currently getting this error. 

HTTPError: 403 Client Error: The user 'bruAristimunha' isn't allowed to upload to project 'Braindecode'. See https://test.pypi.org/help/#project-name for more information. for url: https://test.pypi.org/legacy/

**Comment by agramfort** [comment]
Can you also give me pypi access? 

My login is agramfort 

Thanks

**Comment by robintibor** [comment]
I ahve given you access @agramfort , I need to know your account on PyPI @bruAristimunha

**Comment by bruAristimunha** [comment]
Hi Robin. I think it's bruAristimunha.

**Comment by robintibor** [comment]
ah right unfortunately made some typo before, now you should have an invitation for access

**Comment by robintibor** [comment]
great work
