### ISSUE TITLE
Some questions about TCN

### ISSUE THREAD

**Issue by Ainavo** [braindecode/braindecode#424]
Why braindecode TCN uses dropout2D instead of dropout?

![image](https://user-images.githubusercontent.com/57820731/196412709-d1ffbeb0-0163-468c-9b9b-6c1c8534279a.png)
[braindecode/model/tcn.py](https://github.com/braindecode/braindecode/blob/master/braindecode/models/tcn.py)
![image](https://user-images.githubusercontent.com/57820731/196412771-99c248cb-deeb-4186-84ae-1db694f11fda.png)
[TCN/tcn.py](https://github.com/locuslab/TCN/blob/2f8c2b817050206397458dfd1f5a25ce8a32fe65/TCN/tcn.py#L22)

**Comment by martinwimpff** [comment]
Hi @Ainavo, Dropout and Dropout2d are different from each other. [Dropout2d](https://pytorch.org/docs/stable/generated/torch.nn.Dropout2d.html) randomly zeros out entire feature maps, whereas [Dropout](https://pytorch.org/docs/stable/generated/torch.nn.Dropout.html) randomly zeros out single elements. Does that answer you question?

**Comment by Ainavo** [comment]
@martinwimpff  Thanks for your reply, I would like to know if applying Dropout2D on EEG data works better than Dropout?

**Comment by martinwimpff** [comment]
Try it out and let us know ;) 
In general [this paper](https://arxiv.org/abs/1411.4280) describes the benefits of "spatial dropout".

**Comment by Ainavo** [comment]
Thanks, I'll try it later

**Comment by h1deOnBush** [comment]
Hi,
I tried to test the performence of tcn in bcic_iv_2a. But I don't know how to use this model, I simply replace
`model = ShallowFBCSPNet(
    n_chans,
    n_classes,
    input_window_samples=input_window_samples,
    final_conv_length='auto',
)`
in plot_bcic_iv_4_ecog_trial.py
to
`model = TCN(
    n_in_chans=n_chans,
    n_outputs=n_classes,
    n_blocks=2,
    n_filters=12,
    kernel_size=4,
    drop_prob=0.5,
    add_log_softmax=True
)`
but it just can't work.
And the error is
`RuntimeError: Expected target size [64, 1107], got [64]`
I dont't know how to fix it，I'd be appreciate if you can give me some advice about how to use tcn model in bcic_iv_2a.
