### ISSUE TITLE
How to split dataset with 1 row in description DataFrame

### ISSUE THREAD

**Issue by siji1208** [braindecode/braindecode#425]
when l load the "Cho2017" dataset through 
`dataset = MOABBDataset(dataset_name="Cho2017", subject_ids=[subject_id])` 
l find there is only 1 row in the description DataFrame which results 
`splitted = windows_dataset.split('session')` 
can't work. Is there any other way to split the dataset in this situation?

**Comment by bruAristimunha** [comment]
Hi @siji1208,

I am happy that you are using the braindecode library. Thank you very much for your question, and I hope to be able to help you!

The split function on the windows_dataset object can be used, in any stage, raw or preprocessed. You can use the index from the dataset.description, but you need to decide how and when to do the split when the dataset doesn't have an explicit rule. This question is directly linked to your methodology and what you hope to see with the decoding process.

In the case of the Cho2017 dataset, with the code:

```python
subject_id=[1]
dataset = MOABBDataset(dataset_name="Cho2017", subject_ids=subject_id)
```

You load one raw data from dimensions channels by time (69, 717300). If you are trying to train a single model for multiple subjects, you can do the following split:

```python
subject_id=[1, 2, 3]
dataset = MOABBDataset(dataset_name="Cho2017", subject_ids=subject_id)
dataset.description
splited_dataset = dataset.split(dict(train=[0, 1], test=[2]))
```

Did I understand your question properly?

**Comment by bruAristimunha** [comment]
Hi @siji1208,

Thank you very much for the clarification. Your question is very interesting and fundamental, which could be incorporated into some tutorials. Thanks for contributing to the future improvement of braindecode!

In that case, you need to build the trials (epochs, windows), and after I recommend using PyTorch's subset function.

Code below:

```python
from braindecode.preprocessing import create_windows_from_events

trial_start_offset_seconds = -0.5
# Extract sampling frequency, check that they are same in all datasets
sfreq = dataset.datasets[0].raw.info['sfreq']
assert all([ds.raw.info['sfreq'] == sfreq for ds in dataset.datasets])
# Calculate the trial start offset in samples.
trial_start_offset_samples = int(trial_start_offset_seconds * sfreq)

# Create windows using braindecode function for this. It needs parameters to define how
# trials should be used.
windows_dataset = create_windows_from_events(
    dataset,
    trial_start_offset_samples=trial_start_offset_samples,
    trial_stop_offset_samples=0,
    preload=True,
    window_size_samples=1000,
    window_stride_samples=1000,
)

from sklearn.model_selection import train_test_split
from torch.utils.data import Subset

size_dataset = len(windows_dataset)
train_idx, test_idx = train_test_split(range(size_dataset), 
                                       train_size=0.8, random_state=2409)

windows_train = Subset(windows_dataset, train_idx)
windows_test = Subset(windows_dataset, test_idx)
```

**Comment by siji1208** [comment]
This really helps me.  Thank you for your reply again!
