### ISSUE TITLE
TUAB data version 3.0.0

### ISSUE THREAD

**Issue by Farzaneh-Taleb** [braindecode/braindecode#430]
excepted file format is not matching with the current version of tuab 3

**Comment by bruAristimunha** [comment]
Hi @Farzaneh-Taleb,

Thank you for your let us know. Can you describe it a little more? I couldn't find the version 3.0 in this website: https://isip.piconepress.com/projects/tuh_eeg/html/downloads.shtml#w_2022

**Comment by Farzaneh-Taleb** [comment]
I received an email from joseph.picone@gmail.com in October 2022 as follow: 
"We are preparing new releases of the TUH EEG data and resources, and
would like to obsolete the older versions since we can no longer support
those. The newer versions contain improved annotations, simpler file
formats (e.g., csv) and a few other corrections that users have pointed
out over the past few years. These new versions will be available online
shortly. We will announce them through our listserv.""

I recently accessed the new version of the data. When I downloaded it, it was annotated with v3.0.0.

**Comment by Farzaneh-Taleb** [comment]
For example I needed to change this method as follow to get it to work: def _parse_description_from_file_path(file_path):
    # stackoverflow.com/questions/3167154/how-to-split-a-dos-path-into-its-components-in-python  # noqa
    file_path = os.path.normpath(file_path)
    tokens = file_path.split(os.sep)
    # expect file paths as tuh_eeg/version/file_type/reference/data_split/
    #                          subject/recording session/file
    # e.g.                 tuh_eeg/v1.1.0/edf/01_tcp_ar/027/00002729/
    #                          s001_2006_04_12/00002729_s001.edf
    version = tokens[-6]
    # year, month, day = tokens[-2].split('_')[1:]
    subject_id = tokens[-1].split('_')[-3]
    session = tokens[-1].split('_')[-2][1:]
    segment = tokens[-1].split('_')[-1].split('.')[0][1:]
    return {
        'path': file_path,
        'version': version,
        # 'year': int(year),
        # 'month': int(month),
        # 'day': int(day),
        'subject': subject_id,
        'session': int(session[1:]),
        'segment': int(segment[1:]),
    }

**Comment by bruAristimunha** [comment]
Okay, I think I understand!

Correct me if I didn't catch any. There was a change in the files in the new version of the dataset, and the parse function is not working anymore. A small adaptation in the current code would be enough to choose which parser to use. Something like if version 3 doesn't parser the year, month and day.

Could you do this PR? Your work can help the open-source community =) I can help you with the review.

Did you find any other @Farzaneh-Taleb issues about the dataset?

**Comment by Farzaneh-Taleb** [comment]
Yes, I think that should be enough! Sure! I would be happy! I will let you know if I find anything else!
