### ISSUE TITLE
Working with custom data in numpy format

### ISSUE THREAD

**Issue by MZeydabadi** [braindecode/braindecode#447]
Hi, I have my data in numpy.array format and wonder how I can convert it to the format that is needed to run the "self supervised learning" example. So the data is a 2D numpy array of shape MxN where M is the number of windows and N is the number of samples in each window. (This is a single channel data). I also have target/label vector of size Mx1 which contains labels (0 or 1) for each window/row. I appreciate your help.

**Comment by robintibor** [comment]
Hi @MZeydabadi did you have a look at https://braindecode.org/stable/auto_examples/plot_custom_dataset_example.html ? :)

**Comment by MZeydabadi** [comment]
Yes, I did and that helped to some extent. Thank you!

**Comment by robintibor** [comment]
Great to hear, then closing this, let me know if there is any further issues. Top parts of  https://colab.research.google.com/drive/1dSmd4XfkLzZwM9axmlIotpzuhwPAWFmS#scrollTo=URkMMzc6tOW1 might also be an inspiration.
