### ISSUE TITLE
Need to analyse .EEG extension Patient data by this module for my Research thesis in Neurology

### ISSUE THREAD

**Issue by drajaytripathi** [braindecode/braindecode#448]
Hi
i am a Doctor /Physician from india, currently doing residency in Neurology superspeciality from a hospital in India

I am in stage of planning for a comparative study between Deep Learning AI solution for EEG analysis vs Expert Neurologist Analysis reporting, that shall be part of my Thesis and will be published as a paper afterwords.

For this i need your help as your AI can report an EEG as far as i have understood. 
We will take data of approx 100 patients who are advised for EEG
In our setup , "Clarity software " is used for EEG and file extension produced is .eeg

can you help me in this project?
I have some knowledge of programming basic level and regularly use computers so i can do tech work on my end without inperson support/only remote support can be enough

We will also publish a paper on the results we get and will name  this deep learning solution name in the paper.

**Comment by bruAristimunha** [comment]
Dear Dr. @drajaytripathi,

I hope this message finds you well. Your research on epilepsy and deep learning is fascinating, and I appreciate your interest in our open-source library.

As an open-source library, we aim to support and provide tools for individuals to develop their research in deep learning and brain decoding. However, we do not offer consultancy services for implementing AI solutions. I apologize for any confusion that may have arisen.

If you are searching for a consultancy service that can help you with this specific task, I recommend looking for contacts directly with researchers who specialize in epilepsy and deep learning or [neuro compay](https://neurotechx-services.com/). Alternatively, you could explore consultancy services that provide dedicated resources for complex research like yours.

At present, to the best of our knowledge, no one in our library is working on an epilepsy project. However, I would be more than happy to connect you with any relevant researchers in our community or provide further assistance in any way possible.

I apologize for not being able to do better, thank you for your understanding, and please let me know if you have any further questions or concerns!
