### ISSUE TITLE
Rethink where to put nn inits

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#45]
Right now, one only used by EEGNet is in nn_init.py another one is inside eegresnet... should both be in nn_init? Or both be in models and private?

**Comment by agramfort** [comment]
simple rule. Only make public what is in an example or in the narrative doc
so you have something to show/say about it

>

**Comment by robintibor** [comment]
Makes sense! Then we should move the one used by EEGNet inside eegnet file ... keep this open here to remind
