### ISSUE TITLE
[(Brainde)Code Sprint] Improve documentation

### ISSUE THREAD

**Issue by PierreGtch** [braindecode/braindecode#455]
**Currently**, the documentation of Braindecode is very research-oriented. Some parts are not clear for new users and some parts are simply not present at all.

---

**The goal** of this meta-issue is to achieve a more user-oriented documentation. This means:
- Add docstrings in the [NumPy/SciPy format](https://numpydoc.readthedocs.io/en/latest/format.html) where they are missing;
- Make sure that every function/class parameter is described;
- Achieve a homogeneous level of documentation across the different functions and classes;
- Revisit the experience of a new user arriving on the doc for the first time.

**Comment by bruAristimunha** [comment]
@apmellot, @Sara04, @dengemann, @jpaillard
