### ISSUE TITLE
[(Brainde)Code Sprint] Refactor the datasets

### ISSUE THREAD

**Issue by PierreGtch** [braindecode/braindecode#456]
**Currently**, the datasets pre-load all the epochs in memory.

---

**The goal** of this meta-issue is to refactor the datasets so that the examples are loaded from disk only when needed at runtime (i.e. during the call to `__getitem__`).

**Comment by bruAristimunha** [comment]
@apmellot, @Sara04, @dengemann, @jpaillard

**Comment by bruAristimunha** [comment]
@robintibor and @tomMoral
