### ISSUE TITLE
Adding braindecode in zenodo

### ISSUE THREAD

**Issue by bruAristimunha** [braindecode/braindecode#459]
To better control the citation and version system and the use of braindecode, it is important to deposit the code in an open repository, such as zenodo. As is done in [pyriemann](https://zenodo.org/record/8059038), [sklearn](https://zenodo.org/record/8098905), [pandas](https://zenodo.org/record/8092754) and several open-source libraries.

Can you do it, @robintibor? It seems simple to me to just upload the GitHub files.

**Comment by robintibor** [comment]
Ok exists now at https://zenodo.org/record/8214377

For reference, documentation for steps to do this automatically:

General guide: 
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

Fixing problem that organisation repos do not show up in zenodo settings:
https://github.com/zenodo/zenodo/issues/1814#issuecomment-620555444

Add all existing releases to zenodo:
https://github.com/zenodo/zenodo/issues/1463#issuecomment-1468932469
