### ISSUE TITLE
CircleCI doc downloading and showing fix

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#492]
https://github.com/braindecode/braindecode/blob/8b2770a0c632ff267ede090ea93dca42d92a247b/.github/workflows/push-artifact-to-circleci.yml#L6

This should be changed to "docs" I guess, cannot do easily from train, can you try @bruAristimunha ? Otherwise I do tomorrow 

That's why we cannot see docs in PRs anymore

**Comment by bruAristimunha** [comment]
sure @robintibor :)

**Comment by bruAristimunha** [comment]
Btw, you can still see the doc, I'll show you tomorrow how I was doing it.
