### ISSUE TITLE
Handle old layers names in `load_state_dict` 

### ISSUE THREAD

**Issue by PierreGtch** [braindecode/braindecode#532]
Some layer names were changed and reorganised (#520 #513) and some might be in the future (#463).
If some weights were saved before those changes, it might not be possible to load them anymore after.

If it is not too complex, we should overwrite the `load_state_dict` method of these models to handle old weights.
Otherwise, we introduce a breaking change.

**Comment by sliwy** [comment]
I see it's gonna be resolved in #520 

In the next steps we can take care of converting all lists of keys to map when loading the model into dicts with key name and expected key name. Then we may have only one method in `EEGModuleMixin` and one dict in every model to map the keys.

**Comment by PierreGtch** [comment]
Closed by #520
