### ISSUE TITLE
 Discrepancy in EEGNet Implementation: Extra Conv2D Layer

### ISSUE THREAD

**Issue by vak-sah** [braindecode/braindecode#554]
**Description**
I was reviewing the EEGNet implementation in this repository and I noticed that there seems to be an extra `Conv2D` layer compared to the original implementation of EEGNet provided by the authors at [arl-eegmodels](https://github.com/vlawhern/arl-eegmodels/blob/master/EEGModels.py).

**Details**
- Braindecode Implementation: https://braindecode.org/stable/_modules/braindecode/models/eegnet.html#EEGNetv4
- Original Implementation: https://github.com/vlawhern/arl-eegmodels/blob/master/EEGModels.py

The additional `Conv2D` layer I am referring to is the `conv_classifier` layer, defined as follows:

```python
self.add_module(
    "conv_classifier",
    nn.Conv2d(
        self.F2,
        self.n_classes,
        (n_out_virtual_chans, self.final_conv_length),
        bias=True,
    ),
)
```
**Concern**
This additional layer could potentially affect the performance and behavior of the model, and it might lead to results that are not consistent with the original EEGNet architecture. I wanted to bring this to your attention to clarify if this is an intentional modification or if it might be an oversight.

**Request for Clarification**
Could you please clarify the reason behind this additional layer? If it is indeed a discrepancy, would it be possible to update the implementation to align with the original EEGNet architecture?

Thank you for your time and attention to this matter.

Best,
sahand

**Comment by robintibor** [comment]
Just to also leave an explanation here, this layer corresponds to the dense classification layer in the other implementation https://github.com/vlawhern/arl-eegmodels/blob/4a512e503198db2010848813ead9afbf8cd54c97/EEGModels.py#L151-L152 
In many models in Braindecode, classification layers are implemented as convolutional layers to allow to output a timeseries of class predictions
