### ISSUE TITLE
release 0.8

### ISSUE THREAD

**Issue by bruAristimunha** [braindecode/braindecode#555]
I think we can make a release with what we did in the code sprint.

What do you think @robintibor?

**Comment by bruAristimunha** [comment]
Updated instruction for future bruno:

**Increment version number**
change version number in `braindecode/__version__.py`
change version number in `pyproject.toml`

**Remake docs**
```
cd docs
make rmanddoc
possibly have to do manually before:
make removesource
make removeipynbcheckpoints 
```

Have a look at built html output, copy it to your clone of https://github.com/braindecode/braindecode.github.io into master folder.

**Push docs to master subfolder**
```
cd to your clone of https://github.com/braindecode/braindecode.github.io
git status
possibly git add new stuff
git commit -am 'next version'
git push
```

**Push to pypi** 

You will need to create an API token: https://pypi.org/manage/account/token/

``` 
python -m pip install --upgrade build
python -m build
python -m pip install --upgrade twine
python -m twine upload --repository braindecode dist/*
```

**Create Github Tag**
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Push docs to  main folder**
cd to your clone of https://github.com/braindecode/braindecode.github.io
```
cp -r master/* .
git add appopriate stuff
git commit -am '...'
git push origin master
```

**Comment by bruAristimunha** [comment]
Done @robintibor, I will make the press release next week. If you have any pictures from the code sprint, please let me know (@robintibor, @dengemann, @dcwil, @sylvchev).

I only have the photos at the meta

**Comment by dcwil** [comment]
@bruAristimunha 

I have developed the photos I took, but am still in the process of scanning/inverting them. Hopefully I find some time for this soon, but sorry I couldn't send them over in time for 0.8!
