### ISSUE TITLE
Subject: ModuleNotFoundError: No module named 'braindecode.training' after installing Braindecode 0.8

### ISSUE THREAD

**Issue by Paulhb7** [braindecode/braindecode#559]
Hello!

I have recently installed Braindecode version 0.8, and I encountered an issue when trying to run the following code snippet from the documentation:

```
from braindecode.datasets import MOABBDataset
subject_id = 3
dataset = MOABBDataset(dataset_name="BNCI2014_001", subject_ids=[subject_id])
```

Error Message:

`ModuleNotFoundError: No module named 'braindecode.training'`

**Comment by etiennedemontalivet** [comment]
Same here after fresh installation

**Comment by bruAristimunha** [comment]
Hi @Paulhb7 and @etiennedemontalivet!

I'm sorry about that. If you uninstall braindecode and install it again, everything will work:
```bash
pip uninstall braindecode
pip install braindecode --no-cache-dir
```

We changed the installation system in the last sprint, moving the legacy system from setup.py to pyproject.toml; we are still learning some things.

Thank you very much for using braindecode, and if you can confirm that everything is working, that would be great!

**Comment by bruAristimunha** [comment]
FYI @dcwil

**Comment by dcwil** [comment]
Working for again :D

**Comment by Paulhb7** [comment]
Fixed. Thanks for your work @bruAristimunha !

**Comment by changkun** [comment]
Thank you @bruAristimunha!
