### ISSUE TITLE
Translate Amir Example Code

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#56]
Search your mail for `WG: example code` and translate once new API is integrated

**Comment by robintibor** [comment]
This was written in the old braindecode: https://gist.github.com/robintibor/cf1ce1b8a13b43d27ebca0c022242d50
Task would be to translate this example to current braindecode, so we can send it out to him, maybe renew interest inside.

**Comment by bruAristimunha** [comment]
Hi @robintibor,

Is this still relevant? Amir's code looks like it's already covered by this tutorial, https://braindecode.org/master/auto_examples/plot_sleep_staging_chambon2018.html.

**Comment by robintibor** [comment]
yeah great thanks for checking, thanks for working to keep everything organized
