### ISSUE TITLE
This is not a issue but I have an important question

### ISSUE THREAD

**Issue by bzorzet98** [braindecode/braindecode#579]
Hi, I am using Braindecode and I am very happy to have found this library. I have a question about the implementation of EEGNetv4. Have you done any checks on the results that would allow us to say the implementation is correct? Have you compared the outputs with the outputs of the original Net?

**Comment by bruAristimunha** [comment]
Hey Bruno @bzorzet98!

I don't think so, I wasn't contributing at the time, but knowing the dynamics, I imagine not. Between pytorch and tensorflow there are some differences, in my experience, the EEGNet4net implemented here performs well!

If you want to do some acceptance testing, please let me know, it's a great first contribution and can help the community! The community goes further when we start contributing to the open-source community.

The comparison script would be very simple and could even be generated with chat-gpt...

**Comment by dawin2015** [comment]
> Hi, I am using Braindecode and I am very happy to have found this library. I have a question about the implementation of EEGNetv4. Have you done any checks on the results that would allow us to say the implementation is correct? Have you compared the outputs with the outputs of the original Net?

These are my recently running results on LeftRightImagery paradigm.

id | subj | n_chans | dataset | evaluation | pipeline | avg score
-- | -- | -- | -- | -- | -- | --
0 | 9 | 3 | BNCI2014-004 | CrossSession | EEGInception | 0.849819
1 | 9 | 3 | BNCI2014-004 | CrossSession | EEGNetv4 | 0.837882
2 | 9 | 3 | BNCI2014-004 | CrossSession | ShallowFBCSPNet | 0.824043
3 | 9 | 3 | BNCI2014-004 | CrossSession | TIDNet | 0.820127
4 | 9 | 3 | BNCI2014-004 | CrossSession | Deep4Net | 0.829875

I also try to run the EEGConformer and EEGInceptionMI later.
<img width="311" alt="image" src="https://github.com/braindecode/braindecode/assets/12325204/6bd3fee1-a627-4409-bd9c-8f1e9cc9ead3">

What's more, I am writing a paper about how to design a end-end model on Deep Domain Adaption by using Moabb and Braindecode. It's hard for me. If anyone can help, I would appreciate that.

**Comment by bruAristimunha** [comment]
Nice @dawin2015!

On the moabb side, we gonna released very soon a large benchmark paper that we built for the last whole year, maybe would be interesting in you. As this conversion is not related with the issue, and the issue is "solved", I will closed the issue for now, but we can continue the conversion here. 

FYI @sylvchev.
