### ISSUE TITLE
BCIC IV 2a examples without local path

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#61]
Fetch the BCIC IV 2a data for the realistic examples (`examples/bcic_iv_2a_*`) without relying on downloaded files in a specific folder.

**Comment by robintibor** [comment]
Here are results I get atm:
https://gist.github.com/robintibor/37779c941ad43f6329b7d8ab13a435fe

**Minor** variations due to different machine and GPU indeterminism are okay

**Comment by agramfort** [comment]
you think it's too big to be run on circle ci?

what valid accuracy should I expect on these data?

**Comment by robintibor** [comment]
on CPU, should be too big. results see my last comment

**Comment by agramfort** [comment]
it does not tell me if it's good numbers :)

maybe just one 1 epoch on circle ci?

>

**Comment by robintibor** [comment]
ok fair enough. training on full train set and testing on test set one can reach ~83% on this dataset with our old pipeline (be aware, the random-seed-based variance here can be huge on this dataset. The 83% is averaged across 100 seeds in an internal reproducibility/variance estimation test. 

Maybe someone want to have a try to modify example towards running with 1 epoch per default and using moabb to fetch the data? Without changing any of the remaining/preprocessing code for now to make it easier to pinpoint differences later @sliwy @gemeinl @hubertjb @sbbrandt @TonioBall ? Also find out if we get different epochs from MOABB, e.g., if they throw out epochs marked as artifact-contaminated for BCIC IV 2a. I forgot what we found out there already.

**Comment by robintibor** [comment]
Done
