### ISSUE TITLE
Chambon2018 comments

### ISSUE THREAD

**Issue by OverLordGoldDragon** [braindecode/braindecode#622]
1. ~~`create_windows_from_events` uses `BaseConcatDataset`, which uses `ConcatDataset`, which concatenates across subjects and recordings. Yet, windows fed to `TimeDistributed` should be physically contiguous.~~
 2. https://github.com/braindecode/braindecode/blob/d0c90b5cc271c2e7c0a633644aefd806fd53a00f/examples/applied_examples/plot_sleep_staging_chambon2018.py#L133 should say `# Minimally overlapping windows`
 3. https://github.com/braindecode/braindecode/blob/d0c90b5cc271c2e7c0a633644aefd806fd53a00f/examples/applied_examples/plot_sleep_staging_chambon2018.py#L344 is clearer if it says "Increasing `n_windows`", since "sequence length" can interpret as `window_size_s`.
 4. https://github.com/braindecode/braindecode/blob/d0c90b5cc271c2e7c0a633644aefd806fd53a00f/examples/applied_examples/plot_sleep_staging_chambon2018.py#L6 `We adapt the time distributed approach of [1]_` a difference worth mentioning is, [1] trains the feature extractor on individual windows, then freezes weights, and then trains new classifier with `TimeDistributed`.
 5. https://github.com/braindecode/braindecode/blob/d0c90b5cc271c2e7c0a633644aefd806fd53a00f/examples/applied_examples/plot_sleep_staging_chambon2018.py#L101 [1] standardizes per-window, not per-dataset. Along 4, should be mentioned if the example states it replicates the paper.

Just reporting, I won't be making PRs.

**Comment by OverLordGoldDragon** [comment]
Sorry, scrap 1; I overlooked `SequenceSampler`'s `end_offset`.

**Comment by agramfort** [comment]
John thanks for taking the time here. Just a remark but as you know any
academic open source
software is maintained thanks to the good will of its contributors who
usually work extra hours
to do what they consider "good for science". Any time you take to help here
will benefit
to the scientific progress of the field and I want to stress that it's a
team effort.

**Comment by OverLordGoldDragon** [comment]
A condescending lecture on open source isn't how you get more contributors.

**Comment by agramfort** [comment]
If you think I am lecturing you maybe the developers of braindecode can feel the same way with messages suggesting braindecode could be better ?
