### ISSUE TITLE
Improve Dataset classes and Windower interaction

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#63]
1 Re-fine definition of a BaseDataset:
- does it inherit from pytorch Dataset?
- if it is a pytorch Dataset, length should be n_times
- is there a use case for calling __getitem__?

2 Have a BaseConcatDataset
- should implement a 'split' method

3 Datasets should not know the windower
- move EventWindower / FixedLengthWindower out of MOABBDataset/TUHAbnormal

4 Windowers should be applied to datasets
- Windowers could be functions instead of classes
- windowers should accept a ConcatDataset on __call__ and return a ConcatDataset

5 Avoid variable name ambiguities
- for example with mne.Raw.info

**Comment by hubertjb** [comment]
I've been working on an example for comparing lazy and eager loading on real data (https://github.com/hubertjb/braindecode/blob/lazy-loading-example/examples/plot_lazy_vs_eager_loading.py). I realized there are a few things we might want to add to our design of datasets.

1. Should we add properties to `BaseConcatDataset` to avoid having to go look for information in attributes of attributes, e.g., `concat_ds.datasets[0].raw.info['sfreq']`. Apart from the sampling frequency, other potential properties could be the number of channels, window length, available targets, etc. By using getters with the @property decorator these values could be fetched when needed for example.
2. Currently the data arrays inside the Dataset objects are saved as numpy arrays of type float64. First, knowing the model is usually made out of float32, should we internally cast the data to save space? It could make a difference when using eager loading for instance. Second, should we go a step further and actually store the data as torch Tensors directly, so that we don't need to perform the conversion numpy -> torch before every forward pass?

**Comment by gemeinl** [comment]
1. I've done this before in some of my experiments and included this information in what we now call the <code>description</code> which is a pandas.Series. What do you think about this? One downside would be that we need to manually update the information when we apply transforms (and hence change number of channels, or the sampling frequency). And since we want to support custom transformations, users would need to implement a update of the information...

**Comment by gemeinl** [comment]
2. Where would you apply the casting of float64 to float32? Could this be something which mne or MOABB implements instead? So for example <code>mne.io.read_raw..(dtype=np.float32)</code>.

If repeatedly casting numpy -> torch is slow (as done in the PyTorch DataLoader), we could maybe implement a final transform which handels the conversion once before we train?

Can you maybe include this in your eager vs. lazy loading test to see a) whether it makes a difference to have float32 or float64 and b) whether casting to a Tensor once instead of whenever the DataLoader is called makes a difference?

**Comment by hubertjb** [comment]
>     1. I've done this before in some of my experiments and included this information in what we now call the `description` which is a pandas.Series. What do you think about this? One downside would be that we need to manually update the information when we apply transforms (and hence change number of channels, or the sampling frequency). And since we want to support custom transformations, users would need to implement a update of the information...

Ah good point, it kind of fits nicely into `description`, although I agree that the update part makes it pretty inconvenient. An option would be to make `description` a property itself, and create the `fs`, `n_channels`, etc. entries when the property is accessed. I would either go with that or use basic properties - I think the update solution could too easily become a source of confusion and errors.

**Comment by hubertjb** [comment]
>     1. Where would you apply the casting of float64 to float32? Could this be something which mne or MOABB implements instead? So for example `mne.io.read_raw..(dtype=np.float32)`.

Good point, maybe this could be done by MNE.

> 
> If repeatedly casting numpy -> torch is slow (as done in the PyTorch DataLoader), we could maybe implement a final transform which handels the conversion once before we train?

Also a very good idea!

> Can you maybe include this in your eager vs. lazy loading test to see a) whether it makes a difference to have float32 or float64 and b) whether casting to a Tensor once instead of whenever the DataLoader is called makes a difference?

Yep, thanks for the suggestion, I'll do that as a first step. :)

**Comment by robintibor** [comment]
I would suggest to try to save time here by only implementing here what we already need for some current example to work. E.g., maybe atm only need 'n_channels' and 'fs', then only implement this in a simple way, extend later as needed. When we have a clearer picture from running code what information we really certainly need at which point, these kind of discussions can get simpler.

**Comment by agramfort** [comment]
if you can use the name sfreq for sampling frequency like MNE it would be great.

**Comment by hubertjb** [comment]
> I would suggest to try to save time here by only implementing here what we already need for some current example to work. E.g., maybe atm only need 'n_channels' and 'fs', then only implement this in a simple way, extend later as needed. When we have a clearer picture from running code what information we really certainly need at which point, these kind of discussions can get simpler.

Sure! Actually I think this is not required for making an example work, we can currently do exactly this by accessing attributes of attributes. I was just wondering whether you guys had ideas - we can continue this discussion when it becomes a blocker/ends up in a PR.

**Comment by robintibor** [comment]
Seems done to me.
