### ISSUE TITLE
NVM

### ISSUE THREAD

**Issue by SparklingWasser** [braindecode/braindecode#630]
Please don't mind, it was an issue caused by the old braindecode version that I pinned in Python

**Comment by bruAristimunha** [comment]
Hey @SparklingWasser,

Thank you for reporting, we gonna release soon to solve this issue in the braindecode and in the moabb side. 

FYI. @sylvchev

**Comment by SparklingWasser** [comment]
Thanks @bruAristimunha , I will check that out

**Comment by bruAristimunha** [comment]
I personally recommend using moabb 0.5 until we release the new version @SparklingWasser.

**Comment by SparklingWasser** [comment]
@bruAristimunha Thanks a lot, I will try that one. Thank you!
