### ISSUE TITLE
Suppressing warnings fails when running in parallel

### ISSUE THREAD

**Issue by itsaphel** [braindecode/braindecode#662]
This bit of code:

https://github.com/braindecode/braindecode/blob/master/braindecode/datasets/tuh.py#L410-L413

doesn't work when `n_jobs > 1`. That's ultimately because when using `warnings.filterwarnings` along with joblib (here: https://github.com/braindecode/braindecode/blob/master/braindecode/datasets/tuh.py#L101-L111), the filters aren't carried over to the newly spawned processes.

See also:
* https://github.com/joblib/joblib/issues/1591
* https://github.com/scikit-learn/scikit-learn/issues/12956
* https://stackoverflow.com/questions/65812028/supressing-warnings-during-parallel-execution-with-joblib-in-python/72807161#72807161

There doesn't seem to be any particularly elegant solution to this. The only decent solution I see is appending the filter line to `PYTHONWARNINGS`, which would carry over to spawned processes. That or allowing a supress_warnings parameter to be sent to `BaseDataset.__init__`?

**Comment by bruAristimunha** [comment]
hmmmm, good question @itsaphel. Thank god we have an expert on joblib in the team ;p  @tomMoral, can you give your two cents on the options? 

Do we deal with this inside braindecode or do we do it another way?

**Comment by tomMoral** [comment]
This should be delt with `braindecode` as this is super hard to do in `joblib` ^^.
The best would be to set [this piece of code](https://github.com/braindecode/braindecode/blob/master/braindecode/datasets/tuh.py#L410-L413) directly into [the function called in `PArallel`](https://github.com/braindecode/braindecode/blob/master/braindecode/datasets/tuh.py#L102).

So for instance overloading it in [`TUHAbnormal`](https://github.com/braindecode/braindecode/blob/master/braindecode/datasets/tuh.py#L370) as
```python
    @staticmethod
    def _create_dataset(
        description,
        target_name,
        preload,
        add_physician_reports,
        rename_channels,
        set_montage,
    ):
        with warnings.catch_warnings():
            warnings.filterwarnings(
                "ignore", message=".*not in description. '__getitem__'"
            )
            super()._create_dataset(
                description,
                target_name,
                preload,
                add_physician_reports,
                rename_channels,
                set_montage,
            )
```

**Comment by bruAristimunha** [comment]
hey @itsaphel,

Can you do the PR, please? I can review it for you ;)
