### ISSUE TITLE
Using models/networks as data encoders in isolation

### ISSUE THREAD

**Issue by neerajwagh** [braindecode/braindecode#684]
Hey @bruAristimunha @robintibor ,

Is it possible to use the BD models/networks only for their data encoding/embedding capabilities? What are your thoughts on exposing each model/network as primarily an EEG embedder (user-specified embedding size) with an optional classification/regression layer on top?

My understanding is that this is currently not possible unless I modify the library code directly. Happy to be wrong!

**Comment by bruAristimunha** [comment]
Hey @neerajwagh! Long time!

You can simply initialise the model and remove the last layer, which is always called the `final layer` with Linear Layer. 


```python 

# Reconstruct the model without the last layer
model = nn.Sequential(*list(model.children())[:-1])
```

I feel like it should work, but we may have some issue with some models that don't have an flattened forward, but we can definitely adjustment the forward. You are welcome to open one issue 😊.

Also, I think some models have option `return_features` or something like this, returning things with shape: (batch, n_embed), (batch, n_outputs). In this case you can just pass True and check.

**Comment by neerajwagh** [comment]
Oops, slipped my mind that I could edit these layers after init. Thanks for the reminder!
