### ISSUE TITLE
Improve braindecode.signalproc

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#73]
- Functions <code>exponential_running_standardize</code> and <code>exponential_running_demean</code> should be adapted to accept <code>data</code> input as <code>n_channels x n_times</code>.
- <code>highpass_cnt</code>, <code>low_pass_cnt</code>, <code>bandpass_cnt</code>, and <code>filter_is_stable</code> should be removed and usages be replaced with mne functions and follwoing transform API (https://github.com/braindecode/braindecode/blob/master/braindecode/datautil/transforms.py#L18).

**Comment by gemeinl** [comment]
I believe something went wrong here. Neither #77 nor #79 implement the changes suggested in this issue.

**Comment by robintibor** [comment]
closed by #80
