### ISSUE TITLE
Remove mne_ext

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#74]
- <code>mne_apply</code> and <code>common_average_reference_cnt</code> should be removed and replaced with mne functions through the transforms API (https://github.com/braindecode/braindecode/blob/master/braindecode/datautil/transforms.py#L18)
- <code>concatenate_raws_with_events</code> could potentially be replaced by <code>mne.concatenate_raws</code>. However, this modifies the first raw in-place which is probably not intended. Furthermore, there might be a bug, where events of raws are not properly combined. To be tested. If there actually is a bug, report to mne.

**Comment by agramfort** [comment]
pass a raw.copy() to mne.concatenate_raws if you don't want any inplace
modification
but I agree that functions if not copy param is present should not modify
objects
inplace

>
